### ISSUE TITLE
有个建议

### ISSUE THREAD

**Issue by DaokunBai** [JiongXing/PhotoBrowser#1]
1、当手指拖动图片不放，往下拉时，可以看到背后的控制器，但是此时控制器的状态栏是隐藏的，微信在此状态下，背后的控制器状态栏是不隐藏的。
2、还有一个需求，能不能新增一个 page 的展示方式，类似新浪微博图片浏览，图片浏览时，page 展示在顶部，样式为  1/9，这样可以让用户自行选择。
之前使用的是另外一个库 SKPhotoBrowser， 也是实现的类似功能，但是没有单击退出，长按回调等接口，所以改用这个库，有问题会及时反馈!

**Comment by JiongXing** [comment]
感谢建议，我改进下

**Comment by JiongXing** [comment]
第2点，page的展示方式，我已经做成可自由定制，并默认提供了UIPageControl和 1/9这两种样式方便选择。pod version为0.1.10，你看看

**Comment by JiongXing** [comment]
你提的第1点，状态栏隐藏问题，我还没有找到好的方法，如果你有的话，一定告诉我~

**Comment by JiongXing** [comment]
第1点，状态栏的问题已经解决

**Comment by DaokunBai** [comment]
作者真效率。
最近又碰到两种情况：
1、当图片未铺满屏幕时，点击、双击、拖拽图片显示区域以外的黑色区域无响应操作，微信在此种情况下的有响应操作。此需求看是否需要。
2、当图片在放大情况下，拖拽图片，此时图片会突然缩小为原图，有些突兀，微信在此情况下，拖拽时不会突然改变图片大小。看看这个要不要调整。
另外我最近也看了下这个框架，有时间会 pull 代码
