### ISSUE TITLE
photoBrowserDelegate should use weak property

### ISSUE THREAD

**Issue by JanzTam** [JiongXing/PhotoBrowser#10]
## First issue:
I used `photoBrowserDelegate = self`. It will called recycle retain and ViewController will not dealloc.
photoBrowserDelegate should use weak property.

**This is my code which it's fixed the issue:**

before:
```swift
public protocol PhotoBrowserDelegate {
}

var photoBrowserDelegate: PhotoBrowserDelegate?
```
after:
```swift
public protocol PhotoBrowserDelegate: class {
}

 weak var photoBrowserDelegate: PhotoBrowserDelegate?
```
## second issue:
Had some UI problem on iPad when i rotate iPad.
This code it not used on iPad. 
```swift
/// 禁止旋转
    public override var shouldAutorotate: Bool {
        return false
    }
```
Can u fix it? Thanks man!

**Comment by JiongXing** [comment]
Thank you!

**Comment by JiongXing** [comment]
您好，
第1个问题，我已采纳你的建议修复为weak。
第2个问题，禁止旋转只对于已经打开了PhotoBrowser时，才会禁止，而对于未进入PhotoBrowser的场景是没有禁止的。您说的情况是在什么时候呢？

**Comment by JanzTam** [comment]
Hi,there. The second issue only happen on iPad , iPhone is normal.
Try to run your code on iPad, and it will reproduce this issue.

**Comment by JiongXing** [comment]
I plan to support rotation later...

**Comment by JiongXing** [comment]
Supported rotation.
