### ISSUE TITLE
Swift 4.1版本的 可以么 

### ISSUE THREAD

**Issue by MuRanJiangXia** [JiongXing/PhotoBrowser#103]
有可用的 4.1 版本么 ？

**Comment by JiongXing** [comment]
可以手动导代码到你的项目，把语法修改为4.1，就几句代码的改动。暂时只能这样了

**Comment by JiongXing** [comment]
README补充了如下说明：
手动导入
请把Source/Core下的所有文件拷贝到你的项目。
如果需要使用Kingfisher来加载网络图片，就把Source/Kingfisher下的文件也拷贝到你的项目。
如果需要加载WebP图片，就把Source/KingfisherWebP下的文件也拷贝到你的项目。

**Comment by MuRanJiangXia** [comment]
UICollectionView+JX.swift

Use of undeclared type 'UICollectionView'
这报错呀

**Comment by JiongXing** [comment]
在这个文件`import UIKit`

**Comment by MuRanJiangXia** [comment]
嗯呢 这个处理有点麻烦呀

**Comment by MuRanJiangXia** [comment]
UIView.ContentMode   
'ContentMode' is not a member type of 'UIView'
这个错误呢？

**Comment by MuRanJiangXia** [comment]
好了 好了 谢谢了 ！！
