### ISSUE TITLE
1.5.1 的这两个方法 在 2.0 里面没有了么？ 隐藏点击图片的方法现在是什么呀 

### ISSUE THREAD

**Issue by MuRanJiangXia** [JiongXing/PhotoBrowser#104]
/// 缩略图所在 view
    func photoBrowser(_ photoBrowser: PhotoBrowser, thumbnailViewForIndex index: Int) -> UIView? {
        return collectionView?.cellForItem(at: IndexPath(item: index, section: 0))
    }
    
    /// 缩略图图片，在加载完成之前用作 placeholder 显示
    /// 返回 nil 直接显示本地图片
    func photoBrowser(_ photoBrowser: PhotoBrowser, thumbnailImageForIndex index: Int) -> UIImage? {
        return nil
    }

**Comment by JiongXing** [comment]
2.0没对所点击图片隐藏了，微信取消了这个特性

**Comment by MuRanJiangXia** [comment]
我用这个 方法 还是 没有隐藏点击的view

**Comment by MuRanJiangXia** [comment]
你这写的 太厉害了，我得好好看看了

**Comment by masterdegithub** [comment]
我是真的没找到2.1.0的安装本地pod仓库都清空重装了，还是最高1.6.1，在search中可以看到2。1。0
![image](https://user-images.githubusercontent.com/45305572/48976136-187a8280-f0bc-11e8-8b19-4b6f2a0676fd.png)

**Comment by masterdegithub** [comment]
> 我是真的没找到2.1.0的安装本地pod仓库都清空重装了，还是最高1.6.1，在search中可以看到2。1。0
> ![image](https://user-images.githubusercontent.com/45305572/48976136-187a8280-f0bc-11e8-8b19-4b6f2a0676fd.png)

我叫几个同事也试了，都只能search到不能安装

**Comment by JiongXing** [comment]
@masterdegithub `pod repo update`后也不行吗？

**Comment by masterdegithub** [comment]
> @masterdegithub
> `pod repo update`更新你的本地仓库，然后在项目目录下`pod update`，这样操作也不行吗？

是的，都试过了，不行

**Comment by JiongXing** [comment]
电脑上pod的master仓库源有没改过？是指向官方的吗

**Comment by JiongXing** [comment]
@masterdegithub 如果网速好的话，试试
```
pod repo remove master
pod setup
```

**Comment by JiongXing** [comment]
我试了几台电脑，不同的网络，都可以呢

**Comment by JiongXing** [comment]
@masterdegithub 我发布了2.1.1版本，你有空再试试能不能拉下来？
此issue先关闭，还有问题请在[#106](https://github.com/JiongXing/PhotoBrowser/issues/106)反馈
