### ISSUE TITLE
横屏显示有问题

### ISSUE THREAD

**Issue by MasterMusketeer** [JiongXing/PhotoBrowser#105]
横屏显示大图的时候有问题

**Comment by JiongXing** [comment]
你好，可以具体描述一下问题，或者截图给我吗？

**Comment by masterdegithub** [comment]
![image](https://user-images.githubusercontent.com/45305572/48975054-5c14c280-f0a3-11e8-82ec-69e42307fda4.png)

**Comment by JiongXing** [comment]
v2.1.1版本对模屏做了优化，关闭。
