### ISSUE TITLE
更新不到最新版本   pod始终是1.6.1版本  更新了pod

### ISSUE THREAD

**Issue by xuhuaping** [JiongXing/PhotoBrowser#106]

**Comment by JiongXing** [comment]
podfile没有指定版本吧？pod search 能搜索到吗？是用 pod update 命令更新吗？

**Comment by JiongXing** [comment]
@xuhuaping 发布了2.1.1版本，有空试试能不能拉下来

**Comment by xuhuaping** [comment]
> @xuhuaping 发布了2.1.1版本，有空试试能不能拉下来
  
可以了  不支持ios8.0吗？

**Comment by JiongXing** [comment]
用了9.0的API，不支持8了
