### ISSUE TITLE
loader协议

### ISSUE THREAD

**Issue by masterdegithub** [JiongXing/PhotoBrowser#107]
loader协议中不应该直接传url，应该传个Params的字典，方便接入其他下载方式

**Comment by JiongXing** [comment]
多谢提出，我想下

**Comment by JiongXing** [comment]
如果有具体点场景给我参考一下好了

**Comment by masterdegithub** [comment]
比如我要使用google的RGPC做下载，传的参数不是url，传过来可能只有一个key

**Comment by masterdegithub** [comment]
图片浏览器好像没有看到是否显示状态栏的api，建议添加

**Comment by JiongXing** [comment]
嗯好

**Comment by JiongXing** [comment]
3.0版本已经完全让用户自行加载图片等资源。有需要感兴趣可以看看。
