### ISSUE TITLE
新版本 预览长图问题

### ISSUE THREAD

**Issue by shen0607** [JiongXing/PhotoBrowser#108]
新版本预览长图，停止在长图中间，无法上下滑动，得放大或者缩小后才可以拉动上下

**Comment by JiongXing** [comment]
额，今天修复下

**Comment by JiongXing** [comment]
@shen0607 我看了不会啊，你是说横屏的时候么？

**Comment by JiongXing** [comment]
这里有坑，我再细细想下

**Comment by shen0607** [comment]
wkwebview上面的图片预览，可以获取到placepicture么

**Comment by JiongXing** [comment]
获取图片的代码要你自己写才行

**Comment by JiongXing** [comment]
如果是用`LocalDataSource`的话，localImage就是在浏览器中的图片，与H5的无关

**Comment by JiongXing** [comment]
2.1.2已修复，你看看

**Comment by shen0607** [comment]
好的，这个 能不能 根据 Swift版本，控制里面的方法啊。我的是4.0的，没办法pod还是挺麻烦的。

**Comment by JiongXing** [comment]
我看看弄个4.0低版本的吧
