### ISSUE TITLE
pod search can't find JXPhotoBrowser

### ISSUE THREAD

**Issue by MrCoderMSH** [JiongXing/PhotoBrowser#11]
![Uploading WX20170712-152800@2x.png…]()

**Comment by MrCoderMSH** [comment]
上传图片一直不成功  直接贴error信息吧：
➜  ~ pod search JXPhotoBrowser
[!] Unable to find a pod with name, author, summary, or description matching `JXPhotoBrowser`

**Comment by JiongXing** [comment]
试一下pod setup，更新repo后，再搜看看？

**Comment by MrCoderMSH** [comment]
pod setup之后无法搜到，完全卸载cocoapods之后还是无法搜到

**Comment by JiongXing** [comment]
- -|

**Comment by JiongXing** [comment]
~ ~||

**Comment by MrCoderMSH** [comment]
已解决，可以正常pod install 但仍然无法pod search正常查找

**Comment by JiongXing** [comment]
嗯，感谢提出来，我看看是什么原因

**Comment by iOSleep** [comment]
@MrCoderMSH pod search 有缓存你可以尝试重新构建看看
rm ~/library/cache/cocoapods/search_xxx.json (你找下就知道了)
然后 pod search

**Comment by JiongXing** [comment]
您好，我删除过search文件，删除cocoapods，然后重新安装，pod repo update，
是能搜到pod 'JXPhotoBrowser', '~> 0.3.1'
还没找到你的情况是什么原因..

**Comment by JiongXing** [comment]
您好，请问现在能搜到不？pod search JXPhotoBrowser
