### ISSUE TITLE
下滑渐变缩放中,有没有提供隐藏其他控件的方法

### ISSUE THREAD

**Issue by errorUserInfo** [JiongXing/PhotoBrowser#111]

**Comment by JiongXing** [comment]
在`1.6.x`版是有的，`2.x`新版去掉了，因为我看微信也去掉了这个特性

**Comment by errorUserInfo** [comment]
谢谢

**Comment by errorUserInfo** [comment]
> 在`1.6.x`版是有的，`2.x`新版去掉了，因为我看微信也去掉了这个特性

微信貌似没有去掉这个特性吧,向下滑动时隐藏了其他控件

**Comment by errorUserInfo** [comment]
> 我是看朋友圈的图片效果的

1.6x的哪个方法和属性是有的

**Comment by JiongXing** [comment]
可能我指的效果和你指的效果不一样，你可以截图说明下是怎样的吗？
另外1.6版本可以通过设置转场动画类型`.scale`，并实现相应代理方法就可以有隐藏原缩略底图的效果

**Comment by JiongXing** [comment]
3.0新版本图片下滑时，在`JXPhotoBrowserImageCell`的`onPan`方法，`case .changed:`那里可以获取到当前下滑程度，框架默认隐藏了页面指示器。
感兴趣可以看看。issue我先关闭
