### ISSUE TITLE
缩略图和原图尺寸不一样的时候会出现问题

### ISSUE THREAD

**Issue by masterdegithub** [JiongXing/PhotoBrowser#114]
在超大图的时候缩图的尺寸可能不和原图尺寸一样，导致查看原图的时候尺寸比例还是和缩图比例一样（缩图可能是被截取过）

**Comment by JiongXing** [comment]
感谢提出，我优化下

**Comment by MuRanJiangXia** [comment]
你好，需求和微博  长图显示  一样。点击的时候  缩放效果 不是很好呀 
![Uploading WechatIMG5.jpeg…]()
![Uploading WechatIMG6.jpeg…]()

**Comment by MuRanJiangXia** [comment]
你好，需求和微博 长图显示 一样。点击的时候 缩放效果 不是很好呀
![wechatimg5](https://user-images.githubusercontent.com/24642593/50592370-d3bde480-0ece-11e9-9387-5578345b745a.jpeg)
![wechatimg6](https://user-images.githubusercontent.com/24642593/50592377-db7d8900-0ece-11e9-887b-f1550f127ae2.jpeg)

**Comment by JiongXing** [comment]
嗯，我大概知道问题在哪，抽空优化下

**Comment by MuRanJiangXia** [comment]
你这么有爱呀 ，我也发现了 动画和  长图这个 有点问题

**Comment by JiongXing** [comment]
@MuRanJiangXia 如果你可以改的话，提交一下代码给我合

**Comment by MuRanJiangXia** [comment]
@JiongXing 转场动画我不太熟悉呀，你有时间看看吧 ，长图 缩放动画有点问题

**Comment by JiongXing** [comment]
`2.1.3`版本已发布，现在给转场动画传入UIImageView即可解决问题。
```
// 返回"起始/结束"的前置视图
let trans = JXPhotoBrowserZoomTransitioning { (browser, index, view) -> UIView? in
    let indexPath = IndexPath(item: index, section: 0)
    // 获取前置视图
    let cell = collectionView.cellForItem(at: indexPath) as? CustomCell
    return cell?.imageView
}
```
缩略图如果是长图，建议截取长图的顶部区域作缩略图，这样会更连贯。
