### ISSUE TITLE
关于 图片缩放 

### ISSUE THREAD

**Issue by MuRanJiangXia** [JiongXing/PhotoBrowser#116]
cell 的 imageMaximumZoomScale 这个属性修改后不管用呀 最大还是2呗吧 
![simulator screen shot - iphone xr - 2019-01-28 at 19 19 49](https://user-images.githubusercontent.com/24642593/51833194-c0693200-2331-11e9-8e38-d4522362314c.png)

**Comment by JiongXing** [comment]
我看下

**Comment by MuRanJiangXia** [comment]
好了 我定制了 datasource 和 cell  可以了

**Comment by likeSo** [comment]
在JXPhotoBrowserBaseCell.swift内, `imageMaximumZoomScale`在init方法内被赋值给`imageContainer.maximumZoomScale`, 且`imageMaximumZoomScale`没有写didSet, 所以直接给`imageMaximumZoomScale`赋值是无效的.
我在JXPhotoBrowserBaseCell子类的didInit方法内, `imageContainer.maximumZoomScale = 3.5`这样写就可以了

结论是JXPhotoBrowserBaseCell. imageMaximumZoomScale的作用基本相当于一个临时变量, 无法被重写, 也无法在使用前改为自己需要的值.建议把此值改为计算属性用于子类重写, 或者加一个didSet

**Comment by JiongXing** [comment]
感谢反馈，新版修复

**Comment by JiongXing** [comment]
2.x版本已有修复。
3.x版本可在reloadellAtIndex时，对`JXPhotoBrowserImageCell`的`scrollView.maximumZoomScale`属性赋值。
