### ISSUE TITLE
Compiling for iOS 9.0, but module 'Kingfisher' has a minimum deployment target of iOS 10.0:

### ISSUE THREAD

**Issue by 15620946376** [JiongXing/PhotoBrowser#119]
pod platform 设置为最低的 10.0了， 这个报错该怎么解决呢

**Comment by 15620946376** [comment]
kingfisher 5.2.0 支持最低的版本是10.0了

**Comment by JiongXing** [comment]
podfile限制一下platform试试，
`platform :ios, '9.0'`

**Comment by 15620946376** [comment]
> podfile限制一下platform试试，
> `platform :ios, '9.0'`

因为Kingfisher 5.2.0 最低支持iOS 10， 所以我platform设置为9.0 就没办法使用最新的kingfisher了，所以作者有没有考虑把JXPhotobrowser 最低支持版本也调成10.0 来解决这个问题呢

**Comment by JiongXing** [comment]
9.0还是主流，我只能另出个超前的版本了...

**Comment by JiongXing** [comment]
你好，v2.2.0已发布，此版本兼容Kingfisher5.0
