### ISSUE TITLE
烦请解决Kingfisher的不兼容问题

### ISSUE THREAD

**Issue by AmadeusSys** [JiongXing/PhotoBrowser#120]
如果不想适配Kingfisher5.0以上版本 
烦请在框架中移除对Kingfisher的依赖代码
或调高IPHONEOS_DEPLOYMENT_TARGET到10.0
这种冲突状态下非常难受！

**Comment by JiongXing** [comment]
最晚明天解决

**Comment by JiongXing** [comment]
你好，v2.2.0已发布，此版本兼容Kingfisher5.0

**Comment by AmadeusSys** [comment]
感谢作者
