### ISSUE TITLE
pod 导入 JXPhotoBrowser 不匹配

### ISSUE THREAD

**Issue by ljj756640646** [JiongXing/PhotoBrowser#123]
使用的是swift4  pod 'Kingfisher', '~> 5.0.1'  支持swift 4  JXPhotoBrowser跟Kingfisher不匹配

**Comment by JiongXing** [comment]
更新到v2.2.0看看？支持Kingfisher 5.0了

**Comment by ljj756640646** [comment]
用的是v2.2.0 不行，你重新提交代码了？Kingfisher〜> 5.0.1 好像只支持Swift4.0

**Comment by ljj756640646** [comment]
JXPhotoBrowser 锁定了 Kingfisher 5.3.1 其他版本不行
