### ISSUE TITLE
photobrowser插件再viewdidlaod里添加子view后，在viewwill appear 后自动跑到了collectionview后面

### ISSUE THREAD

**Issue by imfaker** [JiongXing/PhotoBrowser#128]
photobrowser插件在viewdidload添加 内容，所添加的子视图是在 collectionview 之上的 ， 但到了viewWillappear 之后，自动跑到了  collectionview下面。  不知道是何原因 。测试了 demo defaultPageController 插件 ，在 viewdidiload 里面添加内容。 也会出现一样的情况，可是默认在viewdidload 里已经添加了 collectionview，再添加 插件内容，此时 顺序是对的，但到了 viewwillappear里collectionview自动  跑到了最顶部 展示。        不知道这个出现的原因是什么。
2.13 版本 ，最新版本尚未测试

**Comment by JiongXing** [comment]
这个现象我也没有弄清楚，估计是因为我修改了window的level

**Comment by JiongXing** [comment]
3.0新版使用了新的实现方式，已没有此种现象。
先关闭这个issue，若有问题再提问讨论，谢谢~
