### ISSUE TITLE
模拟器测试，下拉时，背景透明度不改变了，真机也是一样，下拉时，背景无透明度改变

### ISSUE THREAD

**Issue by DaokunBai** [JiongXing/PhotoBrowser#13]

**Comment by DaokunBai** [comment]
![qq20170821-112004](https://user-images.githubusercontent.com/13998995/29502454-cb081efa-8662-11e7-8fcf-7bda4ebb2cc0.png)
应该有这个改动导致的，当时是出于什么考虑改的？

**Comment by JiongXing** [comment]
这是为适配屏幕旋转时的改动，考虑不周。马上修复

**Comment by JiongXing** [comment]
暂时先回到了上一版本的代码
