### ISSUE TITLE
怎么到TableViewCell里面使用呢？

### ISSUE THREAD

**Issue by tyzChar** [JiongXing/PhotoBrowser#131]
怎么到TableViewCell里面使用呢？

**Comment by tyzChar** [comment]
封装了一个UIView来操作

**Comment by JiongXing** [comment]
外边控制器也可以，把Cell的事件传出去就行

**Comment by tyzChar** [comment]
> 外边控制器也可以，把Cell的事件传出去就行

`/// 查找同一父级目录下的IVPSImageViewerView
    private func findSameLevelIVPSImageViewerView() -> (imageViews:[IVPSImageViewerView]?, urls:[String]?){
        
        var imageViews = [IVPSImageViewerView]()
        var urls = [String]()
        
        if (self.next?.isKind(of: UIView.self))!{
            let supView: UIView = self.next as! UIView
            var i: Int = 0
            for view in supView.subviews {
                if view.isMember(of: IVPSImageViewerView.self){
                    weak var imageView: IVPSImageViewerView? = view as? IVPSImageViewerView
                    
                    imageViews.append(imageView!)
                    urls.append(imageView!.imageUrl)
                    imageView!.index = i
                    i = i+1
                }
            }
        }
        return (imageViews, urls)
    }`
感觉这样方便一些，您觉得呢？

**Comment by tyzChar** [comment]
> 外边控制器也可以，把Cell的事件传出去就行

`  @objc private func tapAction(){
        (self.imageViews, self.urls) = self.findSameLevelIVPSImageViewerView()
        // 数据源
        let dataSource = JXLocalDataSource(numberOfItems: {
            // 共有多少项
            return self.imageViews.count
        }, localImage: { index -> UIImage? in
            // 每一项的图片对象
            return self.imageViews[index].imageView.image
        })
        // 视图代理，实现了光点型页码指示器
//        let delegate = JXDefaultPageControlDelegate()
        let delegate = PostImageBrowserDelegate()
        // 转场动画
        let trans = JXPhotoBrowserZoomTransitioning { (browser, index, view) -> CGRect? in
            let cell = self.imageViews[index]
            return JXPhotoBrowserZoomTransitioning.resRect(oriRes: cell.imageView,to: view)
        }
        // 打开浏览器
        JXPhotoBrowser(dataSource: dataSource, delegate: delegate, transDelegate: trans)
            .show(pageIndex: self.currentIndex)
    }`

**Comment by tyzChar** [comment]
> 外边控制器也可以，把Cell的事件传出去就行

`@objc private func tapAction(){
        (self.imageViews, self.urls) = self.findSameLevelIVPSImageViewerView()
        // 数据源
        let dataSource = JXLocalDataSource(numberOfItems: {
            // 共有多少项
            return self.imageViews.count
        }, localImage: { index -> UIImage? in
            // 每一项的图片对象
            return self.imageViews[index].imageView.image
        })
        // 视图代理，实现了光点型页码指示器
//        let delegate = JXDefaultPageControlDelegate()
        let delegate = PostImageBrowserDelegate()
        // 转场动画
        let trans = JXPhotoBrowserZoomTransitioning { (browser, index, view) -> CGRect? in
            let cell = self.imageViews[index]
            return JXPhotoBrowserZoomTransitioning.resRect(oriRes: cell.imageView,to: view)
        }
        // 打开浏览器
        JXPhotoBrowser(dataSource: dataSource, delegate: delegate, transDelegate: trans)
            .show(pageIndex: self.currentIndex)
    }`

**Comment by tyzChar** [comment]
> 外边控制器也可以，把Cell的事件传出去就行

`/// 点击浏览 - 默认
    @objc private func tapAction(){
        (self.imageViews, self.urls) = self.findSameLevelIVPSImageViewerView()
        // 数据源
        let dataSource = JXLocalDataSource(numberOfItems: {
            // 共有多少项
            return self.imageViews.count
        }, localImage: { index -> UIImage? in
            // 每一项的图片对象
            return self.imageViews[index].imageView.image
        })
        // 视图代理，实现了光点型页码指示器
//        let delegate = JXDefaultPageControlDelegate()
        let delegate = PostImageBrowserDelegate()
        // 转场动画
        let trans = JXPhotoBrowserZoomTransitioning { (browser, index, view) -> CGRect? in
            let cell = self.imageViews[index]
            return JXPhotoBrowserZoomTransitioning.resRect(oriRes: cell.imageView,to: view)
        }
        // 打开浏览器
        JXPhotoBrowser(dataSource: dataSource, delegate: delegate, transDelegate: trans)
            .show(pageIndex: self.currentIndex)
    }`

**Comment by tyzChar** [comment]
`
/// 点击浏览 - 默认
    @objc private func tapAction(){
        (self.imageViews, self.urls) = self.findSameLevelIVPSImageViewerView()
        // 数据源
        let dataSource = JXLocalDataSource(numberOfItems: {
            // 共有多少项
            return self.imageViews.count
        }, localImage: { index -> UIImage? in
            // 每一项的图片对象
            return self.imageViews[index].imageView.image
        })
        // 视图代理，实现了光点型页码指示器
//        let delegate = JXDefaultPageControlDelegate()
        let delegate = PostImageBrowserDelegate()
        // 转场动画
        let trans = JXPhotoBrowserZoomTransitioning { (browser, index, view) -> CGRect? in
            let cell = self.imageViews[index]
            return JXPhotoBrowserZoomTransitioning.resRect(oriRes: cell.imageView,to: view)
        }
        // 打开浏览器
        JXPhotoBrowser(dataSource: dataSource, delegate: delegate, transDelegate: trans)
            .show(pageIndex: self.currentIndex)
    }
`

**Comment by JiongXing** [comment]
假如你的Cell里面有9张小图，点击某张小图的时候，把这张图的View和序号传到外面那个拥有Cell数据源的类去，让那个类来调起JXPhotoBrowser。这样不需要Cell去数视图。谁管理数据源，就谁去打开新界面。
