### ISSUE TITLE
JXPhotoBrowserProgressView很久不显示

### ISSUE THREAD

**Issue by junstor** [JiongXing/PhotoBrowser#132]
JX你好：

在使用过程中遇到这样一个问题，有些时候打开图片浏览器，默认显示缩略图并下载高清图的过程中，ProgressView不会马上显示，有时候要等很久才会显示出来。

我猜测可能和当时的网络情况有关，比如DNS解析可能花了较长时间，看你代码中是直接用的Kingfisher的progressBlock，并且判断得到的totalSize > 0时才开始显示ProgressView，如果因为网络原因要很久才能得到图片的完整信息，这段时间会不会造成ProgressView无法显示而停留在模糊的缩略图状态，用户还得不到反馈。能否考虑改进下逻辑，当浏览器被打开并且存在高清图需要下载时，直接先显示出ProgressView，可以一直停在0%的状态，因为本身DNS解析和前期网络请求本身应该也算loading的一部分？

**Comment by JiongXing** [comment]
嗯，感谢提出

**Comment by JiongXing** [comment]
这个前几个版本已经优化了。新的3.0版本，例子工程也有示范使用ProgressView，感兴趣可以看看。
先关闭这个issue，若有问题再提问讨论，谢谢~
