### ISSUE TITLE
2.2.3版本出现delegate崩溃bad access ，2.2.1没有问题。。

### ISSUE THREAD

**Issue by codeisjobs** [JiongXing/PhotoBrowser#133]
创建JXPhotoBrowserBaseDelegate以及子类对象后都无法设置属性，不然就报错。换成2.2.1版后就没事。测试为 删除后重新安装最新库，报错，再删除安装2.2.1版，不报错。应该不是我的代码问题。

**Comment by JiongXing** [comment]
感谢反馈，尽快处理

**Comment by JiongXing** [comment]
我没复现出来，查不到原因。你还记得一些具体的报错信息吗？

**Comment by codeisjobs** [comment]
> 我没复现出来，查不到原因。你还记得一些具体的报错信息吗？

好的，我去复现一下

**Comment by JiongXing** [comment]
试试在我的Example工程能复现出来不？

**Comment by codeisjobs** [comment]
额，我刚刚试了下最新的版本，又不报错了，这下真不知道上次的错误信息了。。。。假如我下次遇到了再记录吧，不好意思了🙏🏻

**Comment by JiongXing** [comment]
嗯嗯，更新后可能要clean一下Xcode缓存才行....
