### ISSUE TITLE
请问如何拿到displayingContentView的远程URL?

### ISSUE THREAD

**Issue by likeSo** [JiongXing/PhotoBrowser#134]
利用JXDefaultPageControlDelegate的子类添加了一个下载原图的按钮, 现在的问题是我只找到了displayingContentView拿到当前显示的cell的imageView, 但是拿不到当前cell对应的URL. 
cell.imageView.image可能会出现拿到的是占位图的情况

**Comment by likeSo** [comment]
但是其实还有一个问题,如果说拿到了URL,还是需要自己下载一遍,鉴于图片浏览器本身就是在加载图片,所以我想这里的问题应该是: 能否新增displayingContentView的图片下载进度,以及下载失败后的resume功能?

**Comment by JiongXing** [comment]
图片下载逻辑其实可以完全自定义，自实现PhotoLoader就行

**Comment by JiongXing** [comment]
我先想想你遇到的问题，后面再回复

**Comment by likeSo** [comment]
好的谢谢, 我现在的解决办法是通过displayingContentView.accessibilityIdentifier来判断展示的是本地图片(占位图)还是网络图片
我这里的需求是,点击下载按钮把图片保存到相册,所以逻辑还是要写在delegate里面的吧,与PhotoLoader的功能好像不符?😂

**Comment by JiongXing** [comment]
新版3.0现在把图片加载完全开放出来让用户自行处理，应该能方便达到需求。感兴趣可以看看。
先关闭这个issue，若有问题再提问讨论，谢谢~
