### ISSUE TITLE
缩小图片闪烁

### ISSUE THREAD

**Issue by fanglinwei** [JiongXing/PhotoBrowser#135]
demo缩小的一瞬间会删一下  和 imageView衔接动画不流畅

**Comment by lingfong** [comment]
从长方形缩小到正方形，图片会闪一下。同求解决

**Comment by lingfong** [comment]
从长方形缩小到正方形，图片在正方形中会闪一下。同求解决
@JiongXing

**Comment by JiongXing** [comment]
@lingfong 这是正方形图片和长方形图片差异过大，视觉落差明显的现象。长图在缩小的时候是等比例缩小，如果正方形图片内容只是长图的一小部分，那么两张图片没法在视觉上重叠，导致感受上闪了一下

**Comment by lingfong** [comment]
> @lingfong 这是正方形图片和长方形图片差异过大，视觉落差明显的现象。长图在缩小的时候是等比例缩小，如果正方形图片内容只是长图的一小部分，那么两张图片没法在视觉上重叠，导致感受上闪了一下

是这个原因。看朋友圈它的过渡比较流畅，想达到类似的效果。
试了imageview的各种模式，猜测朋友圈是将缩小图正好和大图的缩小版重合了，但是我还没有解决。
不知道作者有没有啥使用建议，或者从缩放原理上解决这个过渡视觉效果

**Comment by JiongXing** [comment]
只能多实现一种缩小策略，能够和小图重合的才行

**Comment by lingfong** [comment]
感觉朋友圈很鸡贼的在缩放过程中就把图换成了缩小后的图，但是裁剪了。因为缩放过程中太快了，用户感觉不到，不然缩放结束了闪一下就明显了。

**Comment by JiongXing** [comment]
对于当前显示内容与缩略图固定的显示内容不一致的情况，或者用Fade动画来Dismiss会比较好，这个框架可以优化

**Comment by lingfong** [comment]
打算先用fade了，有时间再研究研究这个问题。多谢解惑

**Comment by Kelan-Ju** [comment]
> 对于当前显示内容与缩略图固定的显示内容不一致的情况，或者用Fade动画来Dismiss会比较好，这个框架可以优化

这个闪动比较明显，看着有点难受。请问笔者有好的解决方法吗？

**Comment by JiongXing** [comment]
3.0新版尝试缓解这种前后图片不一致的情况了，感兴趣可以看看。
先关闭这个issue，若有问题再提问讨论，谢谢~
