### ISSUE TITLE
请问支持浏览图片大图过程中添加数据源吗

### ISSUE THREAD

**Issue by shine93** [JiongXing/PhotoBrowser#140]
分页显示图片时，点击进入图片大图浏览器的过程中加载第二页，第三页的数据。

**Comment by JiongXing** [comment]
暂时还没有很好的办法

**Comment by JiongXing** [comment]
你好，新版完全支持动态修改数据源了。感兴趣可以看看。
先关闭这个issue，若有问题再提问讨论，谢谢~
