### ISSUE TITLE
关于跟h5页面交互的时候，图片点击放大后，单击缩小的时候回到原来的尺寸

### ISSUE THREAD

**Issue by soso-su** [JiongXing/PhotoBrowser#142]
关于跟h5页面交互的时候，点击网页拿到图片资源， 图片点击放大后，单击缩小的时候回到原来的尺寸这个怎么展示？我当前是获取不到网页里的imageView的大小的，我拿到的只是图片路径，所以也还不知道图片尺寸，这个有支持这方面的吗

**Comment by JiongXing** [comment]
H5的图片，可以先选用Fade的转场动画。Zoom的方式我也还没完善的办法

**Comment by JiongXing** [comment]
先关闭这个issue，若有问题再提问讨论，谢谢~
