### ISSUE TITLE
collectionView为何不响应scrollViewWillBeginDragging等代理方法

### ISSUE THREAD

**Issue by yyyzzq** [JiongXing/PhotoBrowser#143]

**Comment by yyyzzq** [comment]
JXPhotoBrowserBaseDelegate的scrollViewDidScroll能够触发，但是我往里面加上scrollViewWillBeginDragging这些代理方法就是不触发。。。

**Comment by JiongXing** [comment]
我看看

**Comment by yyyzzq** [comment]
原来是这样，我说怎么找了半天也没发现哪里有问题，多谢🙏
