### ISSUE TITLE
加载图片后，图片被拉伸了

### ISSUE THREAD

**Issue by luluaidota** [JiongXing/PhotoBrowser#144]

**Comment by JiongXing** [comment]
你好，可以在你实例化的`JXPhotoBrowserBaseDelegate`或其子类中，设置`contentMode`属性。
默认值是：
```swift
    /// 图片内容缩张模式
    open var contentMode: UIView.ContentMode = .scaleAspectFill
```

**Comment by luluaidota** [comment]
我这边发现有一张图 在展示的时候，直接就被拉伸了，反复查看，又会出现正常的情况。只有那一张图有出现这个问题。其余的并没有发现

**Comment by joelyou** [comment]
也遇到过类似的情况 就是可能选的是别的相机拍的一些图会出这种情况

**Comment by JiongXing** [comment]
先关闭这个issue，若有问题再提问讨论，谢谢~
