### ISSUE TITLE
文档没更新

### ISSUE THREAD

**Issue by xiongxiongjiang** [JiongXing/PhotoBrowser#148]
JXPhotoBrowser.KingfisherLoader()换成了JXKingfisherWebPLoader，但是文档还是JXPhotoBrowser.KingfisherLoader()

**Comment by JiongXing** [comment]
有两种选择，如果需要显示WebP格式的图片，才需要JXKingfisherWebPLoader。
普通的情况，不用。
podfile也不要写KingfisherWebP
