### ISSUE TITLE
无法再进行Push vc的操作了

### ISSUE THREAD

**Issue by joelyou** [JiongXing/PhotoBrowser#149]
点击查看图片后，比如长按弹出alert后 这时需要Push一个vc 是无法做到的  请问有什么处理思路吗

**Comment by JiongXing** [comment]
一是给PhotoBrowser加导航控制器，二是舍弃基于ViewController改为纯视图。
两种方式我都有考虑优化。
目前的版本只能你自己试试包一层导航控制器后再显示PhotoBrowser看行不

**Comment by joelyou** [comment]
嗯 尝试过第一种 自己包一层导航控制器  但是动画就失效了

**Comment by JiongXing** [comment]
你好，新版3.0已经发布，能很好支持嵌入导航栏。
文档有详细的用法说明，可能需要花一点时间熟悉，谢谢支持~
