### ISSUE TITLE
如何在ViewController -> tableCell -> collectinViewCell 模式中使用本库呢？

### ISSUE THREAD

**Issue by apiapia** [JiongXing/PhotoBrowser#15]
库是这样子调用的
ViewController ->  collectinViewCell 

请问如何在下列的方式中使用呢？
ViewController -> tableCell -> collectinViewCell 

 //在viewController 调起图片浏览器
        let vc = PhotoBrowser(showByViewController: self, delegate: self)

请问能否在cell中调起，或者有更好的方法弄呢？...

**Comment by JiongXing** [comment]
在哪调起，本身是没问题的，只是不推荐在cell内部做这个事。

**Comment by JiongXing** [comment]
在哪调起，本身是没问题的，只是不推荐在cell内部做这个事。页面跳转还是交给viewcontroller吧。
cell的触发事件往外传给vc，再由vc来做delegate和调起吧
