### ISSUE TITLE
关于libwebp

### ISSUE THREAD

**Issue by MuRanJiangXia** [JiongXing/PhotoBrowser#150]
我更新xcode后貌似 不能下载了 ，报错又，之前还是可以下载的
[!] Error installing libwebp
[!] /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp /var/folders/fb/ckkt20dx191b4gdlw278lm5w0000gn/T/d20191029-30579-1foz08a --template= --single-branch --depth 1 --branch v1.0.3

Cloning into '/var/folders/fb/ckkt20dx191b4gdlw278lm5w0000gn/T/d20191029-30579-1foz08a'...
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out
请问最近遇到过么？

**Comment by JiongXing** [comment]
谷歌的这个地址，翻墙才行。给gitconfig文件配置翻墙代理

**Comment by MuRanJiangXia** [comment]
恩恩，找到原因了。在podfile中加上 source 'https://github.com/CocoaPods/Specs.git'
这个就好了，但是之前有段时间不需要加这个的，只要改了那个git json中的url就好了。
感谢回复！
