### ISSUE TITLE
有空请看一下 ，执行到 imageView.frame = fitFrame 崩溃

### ISSUE THREAD

**Issue by ganlinmeng** [JiongXing/PhotoBrowser#151]
po fitFrame
▿ (0.0, 0.0, 320.0, nan)
  ▿ origin : (0.0, 0.0)
    - x : 0.0
    - y : 0.0
  ▿ size : (320.0, nan)
    - width : 320.0
    - height : nan
加载类似这样的网址：http://images.dunkhome.com/examine-goods-flaw-confirm-image/image/45/RackMultipart20191108-10690-1i4xt72
 是**.dms**文件，临时解决办法是，用Kingfisher先加载缓存

**Comment by JiongXing** [comment]
好的我看下，感谢反馈

**Comment by JiongXing** [comment]
http://images.dunkhome.com/examine-goods-flaw-confirm-image/image/45/RackMultipart20191108-10690-1i4xt72 我测试这张图能正常显示。`nan`值的问题，我加一下保护，如果图片加载不出来，就舍弃。

**Comment by ganlinmeng** [comment]
CocoaPods 没发现2.2.6啊 ，我想更新一下看看

**Comment by JiongXing** [comment]
2.2.6推不上cocoapods。稍等下

**Comment by JiongXing** [comment]
好了。防止了nan值发生

**Comment by ganlinmeng** [comment]
老铁可以的！感谢你的努力，给你小星星✨
