### ISSUE TITLE
数据源的问题

### ISSUE THREAD

**Issue by vayneee** [JiongXing/PhotoBrowser#153]
现在是只能一个section的数据源吗？？ 如果是多个section的怎么处理。

**Comment by JiongXing** [comment]
可以多个section的，和section无关。有空我可以补充个使用示例

**Comment by vayneee** [comment]
好的，我先自己再看看。

**Comment by cqswzqcj** [comment]
同问，多个section怎么办

**Comment by vayneee** [comment]
我看了如果多个section的话，openPhotoBrowser该怎么设置数据源，发现要改的东西好像挺多的，我太菜没搞明白，希望可以指点一下，或者补充一个示例。

**Comment by JiongXing** [comment]
稍等，我有个大更新，正在弄

**Comment by vayneee** [comment]
跨section一起浏览的，我看你代码里边section写死了为0，我想改发现在要改的地方好像挺多。

**Comment by cqswzqcj** [comment]
这里作者并没有问题，对于作者封装的预览只需要一个section就好了。大家说的跨section是在自己的页面的collectionView是多个section的时候。这时候需要你们自己把二维数组转成一维数组，转场动画那里根据index从自己的二维数组里面计算出具体的indexPath就好了

**Comment by vayneee** [comment]
好的，这个我想了但是没有做尝试，我尝试一下看看。 之前我是去修改DataSource支持多个section，发现要改的内容很多。就放弃了。

**Comment by JiongXing** [comment]
新版3.0已经发布，对多个section的场景我有举例，可以下载看看。
新版文档有用法说明，可能需要花一点时间熟悉，谢谢支持~
