### ISSUE TITLE
 现在是不是不支持点击过查看原图按钮的图片  再次浏览的时候隐藏查看图片按钮，直接浏览原图

### ISSUE THREAD

**Issue by xiongxiru** [JiongXing/PhotoBrowser#154]
现在的需求就是仿微信聊天页面的浏览模式，对于查看过原图的图片再次浏览的时候直接浏览原图  查看原图的按钮隐藏  
或者我能拿到点击查看原图按钮的回调吗  我看目前好像是拿不到

**Comment by JiongXing** [comment]
其实是支持，这个依赖Kingfisher的缓存，Kingfisher5.0在我原来代码上有点bug，没取到原图的缓存，所以没直接显示出原图。

**Comment by JiongXing** [comment]
我看下怎么修复

**Comment by xiongxiru** [comment]
1、我发现只要传了三级图片的资源  不需要点击查看原图按钮  就直接加载的三级图片的资源  不应该是点击了查看原图之后才会去加载三级图片吗

2、我这边还有个需求就是  进入浏览图片页点击查看原图按钮的图片查看原图之后  关闭图片浏览页  下一次再点击这张图片进入图片浏览页的时候   就不需要展示查看原图按钮了(仿微信聊天页面)  所以我需要拿到查看原图的按钮的点击事件， 希望可以把这个开放出来

**Comment by JiongXing** [comment]
@xiongxiru 我在重构新版本，图片加载完全交给用户管理，但也提供加载范例，新版即将发布

**Comment by xiongxiru** [comment]
好的  谢谢

**Comment by JiongXing** [comment]
你好，新版3.0已经发布，上述问题在3.0中不会存在，例子工程有查看原图按钮的举例。
文档有详细的用法说明，可能需要花一点时间熟悉，谢谢支持~
