### ISSUE TITLE
master 3.0 版本Demo KF加载会崩溃,SD页面不会.不知道原因求解?

### ISSUE THREAD

**Issue by st2340596** [JiongXing/PhotoBrowser#157]
最新版的DEMO ,进KF页面会直接加载图片崩溃. 用SD加载的话就不会崩溃 . 不知道问题在哪

**Comment by JiongXing** [comment]
是DEMO本身的代码就崩溃吗？我看下

**Comment by JiongXing** [comment]
你加载的图片url是？

**Comment by st2340596** [comment]
![image](https://user-images.githubusercontent.com/10336199/70883079-d0066d80-200c-11ea-9404-31f714e847d7.png)
就是这几只猫的地址呀.   直接就崩溃了 . 而且3.0的demo里没有页码指示器的用法.

**Comment by st2340596** [comment]
> 你加载的图片url是？

地址就是demo数据模型里了的,只要是KF加载网络图片的就会崩溃. . 包括下面的多section加载.
0.0 而且与2.0版本的指示器使用方式也更改了.Demo里并没有展示.我在使用的时候如下代码并没有效果.
![image](https://user-images.githubusercontent.com/10336199/70883636-96cefd00-200e-11ea-8671-f10fbd4042e0.png)

**Comment by JiongXing** [comment]
Kingfisher我这边怎么弄都不崩...

**Comment by JiongXing** [comment]
PageIndicator例子现在加一下

**Comment by st2340596** [comment]
> Kingfisher我这边怎么弄都不崩...

我也很不理解为什么KF会崩溃, 是不是因为KF版本的问题?  楼主把KF page删掉重新down进去试试呢.

**Comment by st2340596** [comment]
> PageIndicator例子现在加一下

![image](https://user-images.githubusercontent.com/10336199/70884118-f5e14180-200f-11ea-9eb8-d5e0c5556234.png)
现在KF版本是5.10.1 是不是因为这个版本的问题? 这是package 自动引用的版本

**Comment by JiongXing** [comment]
我的也是5.10.1，demo工程我指定了版本号的，谁下载都一样...

**Comment by JiongXing** [comment]
刚提交了页码指示器的代码，你看看

**Comment by st2340596** [comment]
> 刚提交了页码指示器的代码，你看看

好的 非常感谢

**Comment by JiongXing** [comment]
cocoapods上传比较慢，pod版本还没更新

**Comment by st2340596** [comment]
> cocoapods上传比较慢，pod版本还没更新

 git pull   ... 
看到了最新的demo 辛苦楼主了
难道KF崩溃是我个人的问题?  我再研究一下. 
万分感谢

**Comment by JiongXing** [comment]
你把本地的我以前版本的demo删除，然后工程clean试试
版本更新没有对你们造成困扰就好...

**Comment by st2340596** [comment]
> 你把本地的我以前版本的demo删除，然后工程clean试试
> 版本更新没有对你们造成困扰就好...

我重新clone了master . 
重置了模拟器.
clean了Xcode 重启了电脑
KF依然崩溃. sd依然坚挺 
好郁闷啊
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

**Comment by JiongXing** [comment]
- -||

**Comment by st2340596** [comment]
> * -||

我觉得是kf版本的问题..因为我另外项目需要兼容iOS 8.0 , 就用了KF4.0 来加载图片 ,不会崩溃..

**Comment by JiongXing** [comment]
> 我觉得是kf版本的问题..因为我另外项目需要兼容iOS 8.0 , 就用了KF4.0 来加载图片 ,不会崩溃..
👍

**Comment by JiongXing** [comment]
例子工程我重新改用Cocoapods引入第三方库了，有空可以看看这种方式Kingfisher有没崩溃？
这个issue我先关闭，有问题再重开讨论
