### ISSUE TITLE
建议继续更新使用Kingfisher的版本

### ISSUE THREAD

**Issue by kane3000** [JiongXing/PhotoBrowser#159]
很多人在处理图片时使用Kingfisher，3.0版去除Kingfisher会对使用Kingfisher的用户造成图片的重复下载问题。

**Comment by JiongXing** [comment]
可以继续使用Kingfisher的，不会重复下载的，下载控制在用户手中，框架自身不做下载操作

**Comment by kane3000** [comment]
谢谢，我研究下新版本。

**Comment by JiongXing** [comment]
如果觉得怎么都不好用，或者我再封装一层，但是封装程度越高，灵活性就越差。你有什么建议欢迎提出交流哈

**Comment by chunxige** [comment]
我觉得目前版本这么处理的很好，不依赖任何图片下载库，想用什么自己选，如果工程中已经用了SDWebImage，继续之前的kingfisher版本，工程中会出现两个图片下载库，没必要
