### ISSUE TITLE
这个gift图片似乎无法显示，搞不清楚啥情况，这个链接也不是gift

### ISSUE THREAD

**Issue by fuyunmanbu** [JiongXing/PhotoBrowser#160]
https://gss3.bdstatic.com/7Po3dSag_xI4khGkpoWK1HF6hhy/baike/s%3D500/sign=51eb2484a1af2eddd0f149e9bd120102/48540923dd54564eb5babebbbede9c82d0584f50.jpg

**Comment by JiongXing** [comment]
我试了可以用SDWebImage加载这张gif

**Comment by JiongXing** [comment]
Kingfisher也可以，我提交了一个测试代码，你可以看下。

**Comment by fuyunmanbu** [comment]
我刚刚运行可以显示gift，但是前两天做的时候确实是不行的，目前还没发现问题所在，非常感谢及时回复

**Comment by fuyunmanbu** [comment]
也有可能就是xcode的原因，11.3这几个版本的xcode总是会发生一些奇怪的问题，比如前几天用正则表达式始终无法匹配，结果重启一下xcode就好了
