### ISSUE TITLE
图片的URL有问题加载不了就一直卡着黑屏,点击屏幕不能消失

### ISSUE THREAD

**Issue by Liaoworking** [JiongXing/PhotoBrowser#162]
如题  版本3.0.2   iPhone X     13系统

**Comment by JiongXing** [comment]
我看下

**Comment by JiongXing** [comment]
那个有问题的URL可以发我下吗

**Comment by JiongXing** [comment]
我这边测试即使URL有问题，Kingfisher和SDWebImage都加载不出来，还是可以点击黑屏关闭的。即使把cell的imageView.image = nil，还是可以点击黑屏关闭

**Comment by Liaoworking** [comment]
谢谢   是我的问题  我这边传进来的数组为空。 感恩。
