### ISSUE TITLE
Cannot invoke initializer for type 'JXPhotoBrowser' with no arguments

### ISSUE THREAD

**Issue by Whaiyan** [JiongXing/PhotoBrowser#164]
使用      `  let browser = JXPhotoBrowser()`
初始化的时候，一直报错：

> Cannot invoke initializer for type 'JXPhotoBrowser' with no arguments
![截屏2020-01-11下午6 09 28](https://user-images.githubusercontent.com/22021373/72205529-9e62b400-349d-11ea-9609-5c9b5f3d1476.png)

**Comment by JiongXing** [comment]
应该某些swift版本不支持，我加个显式的初始化方法吧

**Comment by JiongXing** [comment]
你好，我添加了init方法，有空可以更新看看，感谢反馈~
