### ISSUE TITLE
关于 No such module 'JXPhotoBrowser'

### ISSUE THREAD

**Issue by MuRanJiangXia** [JiongXing/PhotoBrowser#172]
No such module 'JXPhotoBrowser'
我更新了   pod  
    pod 'JXPhotoBrowser'
    pod 'JXPhotoBrowser/KingfisherWebP'

    pod 'Kingfisher'

然后就报错了  ，有什么解决 方法么

**Comment by JiongXing** [comment]
如果不指定版本的更新，会更新到最新版，改动还是比较大的，需要看README修改原来的代码。
如果对新版的功能用不到，可以继续使用以前的版本，指定版本号就好。
```
pod 'JXPhotoBrowser', '2.2.6'
```

**Comment by MuRanJiangXia** [comment]
好的 好的谢谢
