### ISSUE TITLE
一张无效的图片，向下滑动收起时会闪退[BUG]

### ISSUE THREAD

**Issue by cbahai** [JiongXing/PhotoBrowser#19]
![wechatimg4](https://user-images.githubusercontent.com/5957012/30429938-f4bfcef0-998b-11e7-833f-b38f67900003.jpeg)  
![wechatimg5](https://user-images.githubusercontent.com/5957012/30430302-634f1938-998d-11e7-9674-91bb06673bdc.jpeg)  

例如这个无效的图片地址：https://ss1.bdstatic.com/70cFvXSh_Q1YnxGssdkpoWK1HF6hhy/it/u=4131634322,487666839&fm=27&gp=0.jpg

**Comment by JiongXing** [comment]
感谢提出

**Comment by JiongXing** [comment]
已修复~
