### ISSUE TITLE
加载图片黑屏

### ISSUE THREAD

**Issue by liangdahong** [JiongXing/PhotoBrowser#199]
在使用 PhotoBrowser 预览网络图片时可能出现黑屏的问题，需要左右切换才可正常显示图片，通过查询源码发现，PhotoBrowser 设置 imgView 的 frame 是在 cell 的 layoutSubviews 里获取 imgView 的 img 的 size 来设置 imgView 的 frame ，但图片通常是异步加载，在下载到图片设置 imgView 的 img 时不会触发 cell 的 layoutSubviews 方法，所以导致 imgView 的 size 可能是 zero【导致黑屏】。同时看了作者 Demo 的做法是：

1. https://github.com/JiongXing/PhotoBrowser/blob/master/Example/Example/KingfisherImageViewController.swift 44 行
2. https://github.com/JiongXing/PhotoBrowser/blob/master/Example/Example/SDWebImageViewController.swift 45 行

在下载到图片后 cell 调用 setNeedsLayout 触发 cell 的 layoutSubviews 方法执行，以给 imgView 设置正确的 size，虽然可以解决问题，但感觉有一些麻烦，而且使用者通常不会注意这个问题，请问作者有优化这个问题的计划吗 ？

**Comment by JiongXing** [comment]
这个事情如果让框架来做也行，优化下，去监听image赋值然后刷新frame



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 梁先森 <notifications@github.com&gt;
发送时间: 2021年2月19日 23:32
收件人: JiongXing/PhotoBrowser <PhotoBrowser@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[JiongXing/PhotoBrowser] 加载图片黑屏 (#199)





 
在使用 PhotoBrowser 预览网络图片时可能出现黑屏的问题，需要左右切换才可正常显示图片，通过查询源码发现，PhotoBrowser 设置 imgView 的 frame 是在 cell 的 layoutSubviews 里获取 imgView 的 img 的 size 来设置 imgView 的 frame ，但图片通常是异步加载，在下载到图片设置 imgView 的 img 时不会触发 cell 的 layoutSubviews 方法，所以导致 imgView 的 size 可能是 zero【导致黑屏】。同时看了作者 Demo 的做法是 https://github.com/JiongXing/PhotoBrowser/blob/master/Example/Example/KingfisherImageViewController.swift 44 行，在下载到图片后 cell 调用 setNeedsLayout 触发 cell 的 layoutSubviews 方法执行，来给 imgView 设置正确的 size，虽然可以解决问题，但感觉有一些麻烦，而且使用者通常不会注意这个问题，请问作者有优化的计划吗 ？

**Comment by liangdahong** [comment]
@JiongXing 是的，比较简洁的方法是自定义 ImgView，重写 setImg 方法即可 😄 。

**Comment by JiongXing** [comment]
修改已放在3.1.3版本发布，可以更新了

**Comment by liangdahong** [comment]
💯
