### ISSUE TITLE
作者真效率。 最近又碰到两种情况：

### ISSUE THREAD

**Issue by DaokunBai** [JiongXing/PhotoBrowser#2]
1、当图片未铺满屏幕时，点击、双击、拖拽图片显示区域以外的黑色区域无响应操作，微信在此种情况下的有响应操作。此需求看是否需要。
2、当图片在放大情况下，拖拽图片，此时图片会突然缩小为原图，有些突兀，微信在此情况下，拖拽时不会突然改变图片大小。看看这个要不要调整。
另外我最近也看了下这个框架，有时间会提交代码

**Comment by JiongXing** [comment]
感谢提出，现已支持点击图外区域，并且放大后拖拽已不会突然缩小
