### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by MrBugDou** [JiongXing/PhotoBrowser#21]
1、建议在类的定义以及协议的定义加上@objc关键字方便OC与Swift混编
2、微信的浏览器在放大的情况下也是可以乡下拖拽dismiss

**Comment by JiongXing** [comment]
好的，感谢您的建议。我看下

**Comment by JiongXing** [comment]
您好，感谢建议，是这样的：
1、对于已有OC代码，不建议由OC来调用swift代码。所以这里不打算支持OC。
2、本库也是支持在放大的情况下，向下拖拽dismiss的，但是需要有一个前提条件，就是图片上方已全部出现在屏幕中，此时再向下拖，就会dismiss。若是图片上方尚有区域有屏幕以外，则下拉只会移动图片以显示屏幕外的区域。

**Comment by zooyf** [comment]
建议:
在README.MD里加入swift版本对应pod版本的说明
