### ISSUE TITLE
这个库存在严重的内容泄露问题

### ISSUE THREAD

**Issue by Mamakou** [JiongXing/PhotoBrowser#214]
1、现实转场动画 会无法释放
browser.transitionAnimator = JXPhotoBrowserZoomAnimator(previousView: { index -> UIView? in
            let photoCell = cell as? DDOBDOperationPhotoCell
           return photoCell?.photoView
       })
2、设置个数的时候会导致 无法释放
browser.numberOfItems = {
    self.dataSource.count
}
改成这样：
let count = self.dataSource.count
browser.numberOfItems = {
    count
}

按照文档来写都能有这么些问题，是实话用的真不放心，希望能改善一下

**Comment by JiongXing** [comment]
已收到反馈，感谢建议

**Comment by danmingyang** [comment]
[weak self]  就可以了吧
