### ISSUE TITLE
JXPhotoBrowserAnimatedTransitioning 协议中关联的photoBrowser 会出现坏内存访问，weak 修饰关联对象使用OBJC_ASSOCIATION_ASSIGN策略

### ISSUE THREAD

**Issue by jiu0929** [JiongXing/PhotoBrowser#217]
![image](https://github.com/JiongXing/PhotoBrowser/assets/23009937/0ab9b4ee-06e5-405e-af3c-8f9ebcdc70e7)

**Comment by JiongXing** [comment]
你好，这看起来是你创建的JXPhotoBrowser对象被释放了。你创建了PhotoBrowser的地方，要保持对PhotoBrowser的引用。

**Comment by jiu0929** [comment]
这个bug 发生在我关闭JXPhotoBrowser 时 ，偶现

**Comment by JiongXing** [comment]
v3.1.5已解决
