### ISSUE TITLE
iOS17下电池栏问题

### ISSUE THREAD

**Issue by huawenhe** [JiongXing/PhotoBrowser#221]
iOS17点击图片放大后电池栏是白色的，图片向下向上拖拽消失后电池栏不见了

![20231113150333](https://github.com/JiongXing/PhotoBrowser/assets/20216749/4ab304eb-d4b5-4820-acac-3b67554eca8c)
![20231113150356](https://github.com/JiongXing/PhotoBrowser/assets/20216749/8c95dedc-c7e0-45c7-8003-f5ec31343596)

**Comment by JiongXing** [comment]
v3.1.5已修改
