### ISSUE TITLE
JXPhotoBrowserAnimatedTransitioning中UIGraphicsBeginImageContextWithOptions已经废弃

### ISSUE THREAD

**Issue by hexiaoba** [JiongXing/PhotoBrowser#223]

**Comment by hexiaoba** [comment]
<img width="709" alt="image" src="https://github.com/JiongXing/PhotoBrowser/assets/13146188/d24f012d-ac22-4b44-a1f4-001a99c5e34e">

**Comment by xiongjuntao** [comment]
"UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={0, 0}, scale=3.000000, bitmapInfo=0x2002. Use UIGraphicsImageRenderer to avoid this assert."  
在snapshot 中 crash了

**Comment by JiongXing** [comment]
v3.1.5已修改
