### ISSUE TITLE
JXPhotoBrowserAnimatedTransitioning中UIGraphicsBeginImageContextWithOptions 出现Crash

### ISSUE THREAD

**Issue by xiongjuntao** [JiongXing/PhotoBrowser#224]

**Comment by xiongjuntao** [comment]
![Uploading 截屏2023-12-26 13.40.24.png…]()

**Comment by xiongjuntao** [comment]
![截屏2023-12-26 13 40 24](https://github.com/JiongXing/PhotoBrowser/assets/14342263/9746b65c-72c2-40d0-b098-8bbdb5dbd7ea)

**Comment by JiongXing** [comment]
v3.1.5已修改
