### ISSUE TITLE
iOS11显示bug

### ISSUE THREAD

**Issue by zooyf** [JiongXing/PhotoBrowser#24]
iOS11，iPhone SE（真机、模拟器均有bug），iPhone X模拟器暂无问题，其他机型未测试

bug描述：

图片高度大于等于屏幕高时，可以发现顶部多出了高20px的黑边，图片向下偏移了20px

![image](https://user-images.githubusercontent.com/10300719/31921990-1538bbd6-b838-11e7-927f-ad24d809d7ff.png)

**Comment by JiongXing** [comment]
thank you.

**Comment by zooyf** [comment]
我刚试了下0.3.7，发现cocoapods中的版本这个bug并没有被修复，兄弟啥时候搞一下

**Comment by JiongXing** [comment]
@zooyf 你用0.4.x的怎么样？swift3旧版本打算停更。
