### ISSUE TITLE
tableView内嵌collectionView的浏览转场动画图片闪烁

### ISSUE THREAD

**Issue by shevakuilin** [JiongXing/PhotoBrowser#27]
在我的tableViewCell内嵌的collectionView中选择除第一个item以外的其他item时，在点击的时候会产生一瞬间图片闪烁的问题，当去掉show方法中的self.modalPresentationStyle = .custom后，问题得以解决，但是效果就没有了，能否告知是何处导致的这个问题，或者希望作者能尝试修复一下

**Comment by shevakuilin** [comment]
慢放检查了一下，应该是放大的动画效果失效了，直接原地消失，然后显示出大图，而不是从小到大的过渡展示，只有第一张图片是正常的从小到大，后面的都是直接原地消失然后展示出大图，所以造成的“闪烁”现象

**Comment by shevakuilin** [comment]
你好，我通过注释掉
public func presentationController(forPresented presented: UIViewController, presenting: UIViewController?, source: UIViewController) -> UIPresentationController?
方法中的animatorCoordinator = coordinator这行代码，临时解决了图片点击前偶尔闪烁的问题，现在一切看起来正常，希望作者检查下animatorCoordinator内的代码隐患

**Comment by shevakuilin** [comment]
问题已具体定位：
/// 更新动画结束后需要隐藏的view
    public func updateCurrentHiddenView(_ view: UIView?) {
        currentHiddenView?.isHidden = false
        currentHiddenView = view
//        view?.isHidden = true  // 此行代码会导致图片在放大前闪烁一次
    }
不知道这句代码当初使用的目的是什么，从效果上看来，屏蔽掉这行代码没发现任何负面影响，并且直接解决了图片闪烁的问题。而直接屏蔽楼上的animatorCoordinator = coordinator这行代码，会导致图片放大左右滑动后（如：从0-->3）图片缩小的返回位置错乱（假设当前是3，返回的位置是1），希望作者回复以告知

**Comment by JiongXing** [comment]
非常感谢，我看下

**Comment by JiongXing** [comment]
您好，请问有能复现这个问题的demo发我看看吗?

**Comment by JiongXing** [comment]
view?.isHidden = true
这行是用来隐藏当前正在显示的大图所关联的前一页面缩略图的，不能去掉。
闪一下的原因，我猜测是因为先做了隐藏，然后再有过渡图覆盖上隐藏的缩略图位置。
把这两个操作顺序换过来应该可以解决。

**Comment by JiongXing** [comment]
但是我尝试过按你说的情景，没有复现问题。你有demo可以发我看看吗

**Comment by shevakuilin** [comment]
当我注释掉view?.isHidden = true
这句代码之后，没有发现任何其他问题，我知道是否是使用不当。是按照你提供的demo里方式调用的，底层图片库由于工程基于sdwebimage，所以替换成了sd的展示方式，但是应该不算这个原因导致的。
demo的话，暂时我没有写，具体就是在tableViewCell中，嵌入一个collectionView，类似微信朋友圈，然后，比如是九宫格图片，除了第一张点开放大、缩小过程正常，其他图片，也就是index
> 0 的图片都会发生高概率图片点之前闪白色一下，类似于原地消失，又重新出现的感觉。
不是每一次都发生，会连续几次不发生闪烁，然后连续几次发生闪烁，这个连续闪烁是针对同一张图。
现在的问题是，不确定具体导致的原因，但是可以定位到大体就是custom转场动画内的问题，因为去掉custom转场动画后，就不会再发生这个闪烁的现象了

2017-11-09 15:21 GMT+08:00 梁炯幸 <notifications@github.com>:

**Comment by shevakuilin** [comment]
“view?.isHidden = true
这行是用来隐藏当前正在显示的大图所关联的前一页面缩略图的，不能去掉。
闪一下的原因，我猜测是因为先做了隐藏，然后再有过渡图覆盖上隐藏的缩略图位置。
把这两个操作顺序换过来应该可以解决。”
这个操作顺序替换的时机是什么？能否举个例子呢

在 2017年11月10日 上午8:41，kuilin xiang <shevakuilin@gmail.com>写道：

**Comment by shevakuilin** [comment]
我将你的原demo中的view?.isHidden = true这句屏蔽掉之后，似乎在效果上也没有受到任何影响，感觉这句代码不是很必要的样子

**Comment by JiongXing** [comment]
在大图上试试下拉图片你就知道这句的作用了，是为了dismiss转场而写

**Comment by JiongXing** [comment]
demo我弄了一个，你试试在上面复现问题，我看看[TestPhotoBrowser](https://github.com/JiongXing/TestPhotoBrowser)

**Comment by shevakuilin** [comment]
在大图上下拉试了一下，没发现和加上这句话的区别在哪里 orz，demo稍后我补一个，最近有点忙

**Comment by JiongXing** [comment]
下拉的话，背景就会透明，然后能看见前一个页面的缩略图了。这句是为隐藏前一页面对应的缩略图而做

**Comment by yszhangjiayu** [comment]
遇到 点击图片 黑屏的情况吗？

**Comment by JiongXing** [comment]
@shevakuilin 您好，在0.4.5版本已经没有对原 view 进行 hidden 操作，应该已经解决了您的问题。若还有出现，请告诉我，感谢~

**Comment by JiongXing** [comment]
@yszhangjiayu 您好，还有出现黑屏情况吗？可以新开一个issue描述一下问题~

**Comment by yszhangjiayu** [comment]
谢谢你




| |
i am a 程序猿；
邮箱：13269734777@163.com
|

签名由 网易邮箱大师 定制

在2018年03月01日 16:13，梁炯幸 写道：

@shevakuilin 您好，在0.4.5版本已经没有对原 view 进行 hidden 操作，应该已经解决了您的问题。若还有出现，请告诉我，感谢~
