### ISSUE TITLE
最新版本点击大图和退出动画不流畅

### ISSUE THREAD

**Issue by lixiaonan** [JiongXing/PhotoBrowser#28]
作者你好, 最新版本点击大图和退出动画不流畅, 旋转时会闪烁一下. 

我手机上最新感觉用微博查看图片也会这样, 
iPhone6s, ios11.0

**Comment by lixiaonan** [comment]
刚刚升级了手机系统, 动画又流畅了😅

**Comment by JiongXing** [comment]
~ ~||
