### ISSUE TITLE
collectionView.scrollToItem(at: indexPath, at: .left, animated: false)

### ISSUE THREAD

**Issue by yszhangjiayu** [JiongXing/PhotoBrowser#29]
creah这里collectionView.scrollToItem(at: indexPath, at: .left, animated: false)，，libc++abi.dylib: terminating with uncaught exception of type NSException，是什么原因？✧(≖ ◡ ≖✿)

**Comment by yszhangjiayu** [comment]
应该是横竖屏导致的原因，

**Comment by JiongXing** [comment]
谢谢，我看看。可以描述一下怎么重现吗

**Comment by JiongXing** [comment]
您好，在0.4.3版本已对横竖屏问题进行过一次修复，应该已解决了您的问题。若还有出现，请告知~
