### ISSUE TITLE
JXPhotoBrowser.show(withImages: [img.image!], currentImageIndex: 0)

### ISSUE THREAD

**Issue by shen0607** [JiongXing/PhotoBrowser#30]
你好，初始化的时候可以增加一个方法，只传 要展示的图片数组和当前显示第几张图片就更好了。类似 let _ = JXPhotoBrowser.show(withImages: [img.image!], currentImageIndex: 0)，因为我目前一个页面有多组图片预览的地方，如果只用代理的话，判断就很多。

**Comment by JiongXing** [comment]
感谢提议，我考虑做一种不用代理的方法

**Comment by JiongXing** [comment]
您还，我想过，像TableView的每个cell里都有一组图片这种情况，那么相比在ViewController里代理所有PhotoBrowser，更好的办法是让每个cell自己代理自己那组图片。
所以您描述的一个页面有多组图片的情况，最好由原来的页面直接对图片操作，改为子区域对图片操作。把复杂的逻辑分离分拆成一个个相对简单的逻辑。

**Comment by shen0607** [comment]
好的，谢谢

**Comment by shen0607** [comment]
好的，谢谢。因为我本来使用的是 XLPhotoBrowser+CoderXL  现在想改成swift版本的库，发现你这个做的很好，就是我转换过来要改的东西比较多了。
