### ISSUE TITLE
急，转场动画不一致的问题

### ISSUE THREAD

**Issue by yangzhixiao** [JiongXing/PhotoBrowser#32]
多张图片，点开第一张，然后滑动到第三张的时候，点击图片，按理说最终动画是回到第三张的，目前是回到第一张，就是一开始点击的那一张，如何解决？
可以提供一个代理，指定最后的endFrame吗？谢谢！

**Comment by JiongXing** [comment]
我查查问题

**Comment by JiongXing** [comment]
`/// 缩放起始视图
    func photoBrowser(_ photoBrowser: PhotoBrowser, thumbnailViewForIndex index: Int) -> UIView? {
        return collectionView?.cellForItem(at: IndexPath(item: index, section: 0))
    }`
这个代理方法正确使用了吗？你希望的endframe，就在index为最后一个时，返回endframe所属那个view给我，就行了。

**Comment by JiongXing** [comment]
/// 缩放起始视图
    func photoBrowser(_ photoBrowser: PhotoBrowser, thumbnailViewForIndex index: Int) -> UIView? {
        return collectionView?.cellForItem(at: IndexPath(item: index, section: 0))
    }
这个代理方法正确使用了吗？你希望的endframe，就在index为最后一个时，返回endframe所属那个view给我，就行了。

**Comment by yangzhixiao** [comment]
@JiongXing 正确使用了的，在最后一次调用的时候，手动设置了view的frame，但是不生效哦

**Comment by yangzhixiao** [comment]
@JiongXing 大神，能帮忙看下吗？

**Comment by JiongXing** [comment]
我重现不了你的问题，找不到原因...

**Comment by yangzhixiao** [comment]
好的，是我的问题，由于您的动画实现，图片是从原来的布局中跳出来，这样会影响我原来的布局，所以我是创建了一个新的view，按照原来的frame，传进去放大，第三次回调再remove掉那个view

**Comment by JiongXing** [comment]
您说的影响原有布局，应该是我把原view进行hidden导致的，如果您使用到UIStackView那种布局容器，hidden确实会有影响，这点倒是我没考虑

**Comment by yangzhixiao** [comment]
嗯，我用的是第三方布局框架，TangramKit，子视图隐藏会引发父视图重新布局；这样一来，用设置透明度为0.01会不会好点？

**Comment by JiongXing** [comment]
已改为0.01透明，更新pod看看

**Comment by yangzhixiao** [comment]
已经更新了，测试了，这种方案没问题，谢谢了
