### ISSUE TITLE
关于[查看原图]按钮

### ISSUE THREAD

**Issue by iFallen** [JiongXing/PhotoBrowser#33]
效果挺好，有个小问题建议哈：
1、加载过程中可不可以隐藏【查看原图】按钮
2、加载完成 【查看原图】没有自动隐藏
或者给个控制 rawImageButton 显示的属性，不然只能导入源文件，修改源文件。
3q!

**Comment by JiongXing** [comment]
好，我看看

**Comment by JiongXing** [comment]
您好，
您说的加载过程，是指加载 highQualityUrl 还是加载 rawUrl 呢？只要 rawUrl 未加载完成，【查看原图按钮】会一直显示。如果不需要原图，则不用实现 rawUrl 代理方法。如果只是某张图不需要原图，则在 rawUrl 代理方法里对应 index  返回 nil 即可。

**Comment by iFallen** [comment]
rawUrl:图片加载过程中，【查看原图】显示，这个时候点击查看原图，案例

**Comment by iFallen** [comment]
rawUrl:
1.图片加载过程中，【查看原图】显示，这个时候点击查看原图，按钮消失，此时若图片加载失败，不会再实现【查看原图】按钮。（建议：加载过程中，走进度的时候，隐藏【查看原图】按钮会好点。失败了再显示出来。）
2.有时候，如果图片很小，或者来源于缓存的图片，图片已经显示了，【查看原图】按钮还在。
👍 :)

**Comment by JiongXing** [comment]
1、加载过程中可不可以隐藏【查看原图】按钮?
重写了取图片相关逻辑，现在加载任意图片都不会出现查看原图按钮，加载完毕后按需出现。
更新到 pod 0.4.6 看看。

**Comment by JiongXing** [comment]
关于查看原图加载失败的问题，如果加载失败了，那么再次加载失败的概率还是很大，我觉得的按钮不应自动重新出现，如果确实需要再次加载，可以滑动到别处在滑回来，这时按钮还是会出现

**Comment by JiongXing** [comment]
2.有时候，如果图片很小，或者来源于缓存的图片，图片已经显示了，【查看原图】按钮还在。
这个问题，按我重写完后的逻辑应该不会有，我没测试出来。若有发现，请再告诉我，蟹蟹~
