### ISSUE TITLE
相册浏览模式，浏览结束时返场时图片与入场时图片不一致时的问题

### ISSUE THREAD

**Issue by gavinning** [JiongXing/PhotoBrowser#36]
场景：
相册模式，启动时是从封面图启动，封面图作为第一张图，当浏览到第二张图片时候返场，这时候原View是没有第二张图片的缩略图的，原View的缩略图是相册封面图，这时候返场动画两张图片切换时就会显得很生硬，请问当前库对这种场景有没有合适的解决方案？

我看了一些的app对类似场景的解决方案【返场时原View没有当前图片时的场景】：
方案1: 返场前会回退到第一张图，然后再开始返场，此时问题解决【Lofter】
方案2: 返场动画会变成渐隐方式，不再缩放到原View缩略图的位置【图虫】

**Comment by gavinning** [comment]
🤣找到了解决方法了，看到``ScaleAnimator.swift``里定义了两种转场方式，有一种是fade用来解决这种场景的，修改了一下代理解决了
```
func photoBrowser(_ photoBrowser: PhotoBrowser, thumbnailViewForIndex index: Int) -> UIView? {
    if index == 0 {
        return imageView
    }
    else {
        return nil
    }
}
```

**Comment by JiongXing** [comment]
机智
