### ISSUE TITLE
首次滑动Bug

### ISSUE THREAD

**Issue by Au12th0psav** [JiongXing/PhotoBrowser#37]
首次进入浏览，用力向右边滑动，页面直接跳到第三页，正常情况应跳到第二页，还请修改一下哈。

**Comment by JiongXing** [comment]
这个问题是由下面这段代码的加页数导致的：
// 处理轻微滑动
if velocity.x > 0.2 {
    page += 1
} else if velocity.x < -0.2 {
    page -= 1
}
如果要根本杜绝这种情况发生的话，就要降低滑页的灵敏度，导致需要滑出很远才能切到下一页。
权衡之后，当时我选择了保留灵敏度，牺牲这种极限操作下的体验。其实用户都这么用力滑了，意思就是想快点翻页，那么就让他翻快一点好了~
如果有更好解决办法，请一定要提出来~

**Comment by cddjr** [comment]
这个我也发现了，最后觉得还是交给系统来处理，没必要自己去弄了

**Comment by JiongXing** [comment]
v0.9.1版本已解决这个问题了，谢谢。
