### ISSUE TITLE
如何取消转场动画 ?

### ISSUE THREAD

**Issue by CivelXu** [JiongXing/PhotoBrowser#38]

**Comment by JiongXing** [comment]
还有这种需求 - -|
只好给你个开关，禁用动画了

**Comment by CivelXu** [comment]
WebView 中图片点击浏览; 找不到 thumbnailViewForIndex

**Comment by JiongXing** [comment]
webView的浏览就不用动画了是吧？我给个禁用选项

**Comment by junstor** [comment]
同求关闭转场动画的方法，我也是webView中用，请问大佬禁用选项加好了吗🤪

**Comment by JiongXing** [comment]
更新到 0.6.0，新增了一种转场动画效果：渐变
```swift
photoBrowser.animationType = .fade
```

**Comment by JiongXing** [comment]
你觉关闭拖拽好点么？我还特意保留了

**Comment by CivelXu** [comment]
因人而异吧。拖拽的时候可以看到 原来的图 有点奇怪

发自我的 iPhone
