### ISSUE TITLE
请问如何得知图片浏览器关闭事件？

### ISSUE THREAD

**Issue by Just2Archi** [JiongXing/PhotoBrowser#39]
非常棒的开源项目，给作者点个赞！

我想在关闭browser后将传入browser的delegate进行释放。
delegate在browser是弱应用，因此在外部需要持有它。
目前的问题是无法得知何时关闭浏览器，导致delegate无法释放。。。

**Comment by JiongXing** [comment]
稍等下，我给个关闭的回调

**Comment by JiongXing** [comment]
已加。更新到0.5.0看看

**Comment by Just2Archi** [comment]
非常！！！感谢~~ 👍
