### ISSUE TITLE
请支持浏览本地图片，不想在用另外的库了

### ISSUE THREAD

**Issue by Cocowyr** [JiongXing/PhotoBrowser#44]

**Comment by Cocowyr** [comment]
/// 图片加载前的placeholder
    func photoBrowser(_ photoBrowser: PhotoBrowser, thumbnailImageForIndex index: Int) -> UIImage? { } 
暂用这个方法预览本地图片，如果是缩略图就不好用了

**Comment by JiongXing** [comment]
嗯，尽快支持

**Comment by CivelXu** [comment]
+ 1 发版本 记得叫一下

**Comment by JiongXing** [comment]
已支持，实现这个协议：
```swift
/// 加载本地图片，本地图片的展示将优先于网络图片
func photoBrowser(_ photoBrowser: PhotoBrowser, localImageForIndex index: Int) -> UIImage? {
    return index == 3 ? UIImage(named: "xingkong") : nil
}
```
其实效果和只用`thumbnailImageForIndex`是一样的，只不过现在给了显式方法。
你所说的预览本地图片，不知道`本地`指的是已经存在的`Image`对象，还是其它？

**Comment by powerDJL** [comment]
本地相册的浏览和本地缓存图片的浏览应该都支持。原理差不多吧。

**Comment by JiongXing** [comment]
@Cocowyr @CivelXu @powerDJL 已支持，用法看5楼。我先关闭issue，若有疑问再打开。

**Comment by Cocowyr** [comment]
好的谢谢

**Comment by KiviBerry** [comment]
能展示本地相册的phasset或者data吗，因为取出来的是本地的gif图片，不是网络gif图

**Comment by JiongXing** [comment]
@KiviBerry 本地的gif图片要展示，只能你自己加载了，因为Kingfisher只能加载url。
如果你可以自己加载本地图片的话，就继承或仿写`JXLocalDataSource`，然后把
```
cell.imageView.image = xxx
```
改为你自实现的加载方法。
目前我没有给出示例，你有时间研究一下。
