### ISSUE TITLE
同时支持视频就太帅了真的

### ISSUE THREAD

**Issue by hydyy** [JiongXing/PhotoBrowser#49]
本来想自己写的，是否考虑会加？不考虑我只能自己想办法了

**Comment by JiongXing** [comment]
支持视频的话，好像有点跑题了，不过，想想也有点小兴奋~
也许能做，为了不影响仅需要图片浏览的用户，会通过可选组件的方式集成。
只是我事情比较多，开发进度不会太快

**Comment by hydyy** [comment]
嗯 期待一下

**Comment by JiongXing** [comment]
具体的视频播放实现，抛出来由用户自己播放，这种方式可以吧？

**Comment by hydyy** [comment]
@JiongXing 播放的实现可以由用户自己实现呀，比如可能我们还需要对视频做本地缓存等等 最好做的开放一些 可定制程度高一些 哈哈哈

**Comment by fuuqiu** [comment]
期待中 虽然目前只是需要图片的功能  但是将来只是视频应该还是一个趋势

**Comment by HMWDavid** [comment]
+1

**Comment by williamxiewz** [comment]
+1

**Comment by ZSMHup** [comment]
+1

**Comment by JiongXing** [comment]
新版本2.0已发布，理论上支持添加任意控件，也可以继承Cell，自由定制。例子项目还没有示范视频，我有空再补上示范例子。

**Comment by MasterMusketeer** [comment]
> 新版本2.0已发布，理论上支持添加任意控件，也可以继承Cell，自由定制。例子项目还没有示范视频，我有空再补上示范例子。

2.0还没有放到pod上

**Comment by JiongXing** [comment]
@MasterMusketeer pod repo update 一下

**Comment by MasterMusketeer** [comment]
> 新版本2.0已发布，理论上支持添加任意控件，也可以继承Cell，自由定制。例子项目还没有示范视频，我有空再补上示范例子。

为什么我的pod search 可以搜到2.0.7但是安装最新的时候只是1.6.1

**Comment by MasterMusketeer** [comment]
> @MasterMusketeer pod repo update 一下

update了还是更新不了

**Comment by JiongXing** [comment]
@MasterMusketeer 在`podfile`文件没有变更的情况下，`pod install`不会改变当前的版本，`pod update`才会升版本

**Comment by MasterMusketeer** [comment]
> @MasterMusketeer 在`podfile`文件没有变更的情况下，`pod install`不会改变当前的版本，`pod update`才会升版本

试过了，先跟新repo 然后pod update，安装的是1.6。1
直接指定版本2.0.7报错找不到对应版本

**Comment by JiongXing** [comment]
3.0已支持，感谢可以看看。
issue先关闭了，有问题再提。谢谢~
