### ISSUE TITLE
数据源中的imageArray没有用吧

### ISSUE THREAD

**Issue by sishenyihuba** [JiongXing/PhotoBrowser#5]
JX兄你好：

拜读了你写的关于怎样定制一款图片浏览器的文章，收益良多，研究代码中发现：

数据源中的imageArray 应该是没有用的吧，Cell的内容都是通过url下载的图片么。

**Comment by JiongXing** [comment]
嗯，本地提供imageArray的情况应该是很少App这样做的，大多数用于展示的图片都是通过url下载。这里只是额外提供方法，支持这种展示本地图片的方式。

**Comment by sishenyihuba** [comment]
嗯嗯。
1.我刚才查看微信的图片浏览器，发现从小图到大图的时候，电池图标是在进入到图片浏览器界面就瞬间消失的，而咱们的是等图片加载完毕才消失。
2. 从大图退到小图的时候，电池图标也是随着StatusBar渐变出现的，而不是咱们现在的直接展现出来。 是微信做了什么特殊处理吗？

**Comment by JiongXing** [comment]
StatusBar的问题确实很纠结，因为这里的实现原理可能与微信不一样...我看下有没办法

**Comment by sishenyihuba** [comment]
从iOS7开始，状态栏就一直就是烦人的东东。不过这个细节有很重要，我也研究研究，有方法了，沟通哈。 我把issue close了先

**Comment by JiongXing** [comment]
现在解决了问题1，我把状态栏的隐藏时间提前了，代价是需要强行取keyWindow。
问题2的话，影响稍微轻点，暂时也没有好的办法。

**Comment by sishenyihuba** [comment]
兄弟效率好高。  实现某些个像是StatusBar这种东东，用下UIApplication也是没有办法的办法么。
