### ISSUE TITLE
为什么下载下来demo不能直接运行

### ISSUE THREAD

**Issue by fuuqiu** [JiongXing/PhotoBrowser#53]
开发环境是swft4.1 xcode9.3 有遇到这种情况的么?

**Comment by JiongXing** [comment]
我看看

**Comment by fuuqiu** [comment]
能编译通过  pod也更新了 但是运行没有任何提示 不能启动模拟器

**Comment by JiongXing** [comment]
模拟器都启动不了？新建一个新项目把模拟器跑起来看看？

**Comment by JiongXing** [comment]
注意选中PhotoBrowser 这个 target 来运行

**Comment by fuuqiu** [comment]
非常感谢 刚开始接触xcode 按照你的方法可以正常运行了
