### ISSUE TITLE
在使用Eureka库自定义表单元素时,如何实现图片浏览的功能

### ISSUE THREAD

**Issue by fuuqiu** [JiongXing/PhotoBrowser#54]
因为自定表单元素的时候,不能继承Controller,在PhotoBrowser库中demo看了下,self都是当前类遵守了Controller以后才能使用,有没有什么方法可以实现传入一个控制器,返回的View我可以使用到其他控件中进行展示呢?

**Comment by JiongXing** [comment]
任何类都可以遵守PhotoBrowserDelegate，不一定要Controller。要弹出浏览器的话，用 show() 方法就行

**Comment by fuuqiu** [comment]
```
import UIKit
import Eureka
import JXPhotoBrowser
//自定义Row
public class MeCell : Cell<UIView>,CellType,PhotoBrowserDelegate{

}

```
 `报错:Type` 'MeCell' does not conform to protocol 'PhotoBrowserDelegate'

现在我在控制层把图片生成 传到表单自己定义的cell 的View中(使用addSubview的方式) 图片可以看到了 但是点击的时候不能显示浏览器全屏的那个效果,代理方法都在控制器中遵循并实现

有那种给浏览器传递图片数组,然后就显示的方法么?

**Comment by JiongXing** [comment]
稍后晚点时间，我示范一下这种场景的用法

**Comment by fuuqiu** [comment]
好的  非常感谢 持续关注中

**Comment by JiongXing** [comment]
你好，新Demo示范了在Cell里实现图片浏览协议，并打开图片浏览器。看看~
