### ISSUE TITLE
图片预览时,当删除当前图片,如何属刷新当前预览器的内容

### ISSUE THREAD

**Issue by fuuqiu** [JiongXing/PhotoBrowser#55]
昨天写删除回调式发现,预览指示器随着照片的删除会动态刷新,但是当前显示的照片变成一块黑色区域.没有刷新图片加载,demo里的预览照片的数据源看了下是固定的,没有因为控制器中的thumbnailImageUrls数组变化.

**Comment by JiongXing** [comment]
可以上传代码让我运行一下么

**Comment by fuuqiu** [comment]
[platform_medicine_ios.zip](https://github.com/JiongXing/PhotoBrowser/files/2020985/platform_medicine_ios.zip)
通常删除最后一张照片会报错,删除前面几张会显示黑色   忘了注释:IdentityAuthViewController.swift第311行  browser.dismiss(animated: false)

**Comment by JiongXing** [comment]
我刚才更新了demo，尝试模拟你的情况，看看有没帮助？你的代码我稍后再看

**Comment by fuuqiu** [comment]
我已经下载最新的demo 如果每张照片都配置为有删除按钮的话  删除最后一张( 页标调整为9/8,显示图片为黑色区域,删除按钮依然存在,再点击异常退出)程序异常中断
我想应该是删除的逻辑中没有判断数据源的count和没有刷新预览view造成   当删除以后,会执行框架中那个方法? 
回调方法能实现图片数据源的动态删除,预览辅助器(页标和删除按钮等装配没有发生变化),当从后往前删除时,就会发生角标越界问题.

**Comment by fuuqiu** [comment]
最后找了一折中的办法 每次删除都关闭预览窗口,删除的时候刷新ell发现不能取到数据,删除动态渲染还是会有一点点问题.感谢大神这几天的帮助

**Comment by JiongXing** [comment]
demo写的不够完善，我今天会再更新一下

**Comment by JiongXing** [comment]
你好，现在已完美支持删除操作~

**Comment by fuuqiu** [comment]
非常感谢 提前赞一个
