### ISSUE TITLE
pod 'JXPhotoBrowser'

### ISSUE THREAD

**Issue by qing-song** [JiongXing/PhotoBrowser#57]
为什么 pod 'JXPhotoBrowser' 安装的版本跟 demo 不一样呢
![image](https://user-images.githubusercontent.com/3859530/40459094-16a6ec62-5f32-11e8-9f1c-a32a5b8fc2b2.png)
![image](https://user-images.githubusercontent.com/3859530/40459120-43afdd86-5f32-11e8-8010-dfd01e5063b0.png)

**Comment by JiongXing** [comment]
执行一下`pod repo update`
