### ISSUE TITLE
请问这个PhotoBrowserDefaultPageControlDelegate在哪里？

### ISSUE THREAD

**Issue by jianjunzhao-github** [JiongXing/PhotoBrowser#58]
更新到1.1.1，没在代码里看到你README里提到的PhotoBrowserDefaultPageControlDelegate？
原来的PhotoBrowserDefaultPageControl也unresolved了。

**Comment by JiongXing** [comment]
PhotoBrowserDefaultPageControlDelegate已经删掉了，页码的插件的集成办法是：
```swift
browser.plugins.append(DefaultPageControlPlugin())
```

**Comment by jianjunzhao-github** [comment]
好的，多谢
