### ISSUE TITLE
 .fade样式; 设置 originPageIndex 无效

### ISSUE THREAD

**Issue by CivelXu** [JiongXing/PhotoBrowser#59]
func photoBrowser(_ photoBrowser: PhotoBrowser, highQualityUrlForIndex index: Int) -> URL? {
}
index 始终为0 
希望修复一下这个bug

**Comment by CivelXu** [comment]
今天更新了版本 出现了大量错误 
修改完 出现了上面 这个 bug 研究了 半天 
以为是自己的代码错误

结果 修改为 .scale 后 就不会出现在 上诉的错误

**Comment by CivelXu** [comment]
看了下 源码 fade 类型下; 没有做转场的 前的布局 
加上 makeScalePresentationAnimator() 里面的布局即可
        setupViews()
        layoutViews()
        // 立即加载collectionView
        let indexPath = IndexPath(item: currentIndex, section: 0)
        collectionView.reloadData()
        collectionView.scrollToItem(at: indexPath, at: .left, animated: false)
        collectionView.layoutIfNeeded()
        let cell = collectionView.cellForItem(at: indexPath) as? PhotoBrowserCell
        let imageView = UIImageView(image: cell?.imageView.image)
        imageView.contentMode = imageScaleMode
        imageView.clipsToBounds = true

**Comment by JiongXing** [comment]
版本改动给你添麻烦了，很抱歉，我现在改，感谢提出

**Comment by JiongXing** [comment]
你好，v1.1.2已修复，看看
