### ISSUE TITLE
求 react native 版本

### ISSUE THREAD

**Issue by musicode** [JiongXing/PhotoBrowser#6]
RN 一直没有仿微信仿的非常好的原生图片浏览组件，你写的组件如果能封装给 RN 用就好了！

**Comment by JiongXing** [comment]
哥你这需求难度不小啊，我...我考虑下！

**Comment by musicode** [comment]
哥，会安卓么！

**Comment by JiongXing** [comment]
基本不会 >,<

**Comment by musicode** [comment]
封装一下 RN 呗，原生都写完了，剩下的只是桥接而已嘛

**Comment by musicode** [comment]
这有个安卓的 [ImageViewer](https://github.com/nesror/ImageViewer)

**Comment by musicode** [comment]
再求 RN 封装...[文档](http://reactnative.cn/docs/0.46/native-modules-ios.html#content)

**Comment by musicode** [comment]
跪求 RN 版，这个库是我目前能找到最好的了，但我不会 swift...

**Comment by JiongXing** [comment]
封装给RN调用么？

**Comment by musicode** [comment]
是的，我简单说个场景。

在文章详情页，包含很多图片，点击其中一张图片，js 可以收集到文章内容中的所有图片，数据格式如下：

```js
[
    { url: '123', width: 100, height: 100 },
   ...
]
```

我把这个数组，再加上当前显示的图片 index 传给 PhotoBrowser 提供的一个接口，比如叫 `show(images, index)`，这时唤起 native 界面，native 界面销毁后，再回到 RN 界面。

如果要支持缩略图、原图啥的，我可以改数据格式，拜托拜托！

**Comment by musicode** [comment]
@JiongXing 有空给个回复呗

**Comment by JiongXing** [comment]
大兄弟，RN相关的我基本上没有开发经验，短期内也没有时间和计划搞这个啊。急的话，可能你真的要找其他人帮你封装一下了...

**Comment by cbahai** [comment]
@musicode 这都要人家弄😳

**Comment by musicode** [comment]
这个库是 0 依赖么？

**Comment by musicode** [comment]
@JiongXing 能否加你 QQ 啊

**Comment by JiongXing** [comment]
目前唯一依赖是 Kingfisher。考虑做个零依赖的版本

**Comment by JiongXing** [comment]
基本不用QQ，微信可以加 liangjiongxing

**Comment by domingoxx** [comment]
所以有人考虑实现RN版本吗， 我打算包一个自己用一下，如果大家有需求可以提出来，我可以开源出来，希望没有打扰到作者。

顺带求一下安卓上面跟这个一样好的图片浏览库

另外感谢作者开源这么好的作品 :)

**Comment by musicode** [comment]
@domingoxx 我的计划是通过原生代码，把这个需求彻底解决，以前实在是浪费我太多时间了

**Comment by domingoxx** [comment]
@musicode 好，我在弄ios得， 我私下联系你。

**Comment by musicode** [comment]
@domingoxx 我给你发了邮件

**Comment by JiongXing** [comment]
新版本2.0已重构完成，大量使用了Swift特性，我想，不太适合封装给RN，暂时也没有这个计划了。
