### ISSUE TITLE
pod库运行有错

### ISSUE THREAD

**Issue by Gdmec07140507** [JiongXing/PhotoBrowser#61]
能顺利pod库，但是运行的时候有一些赋值错误

**Comment by JiongXing** [comment]
请问是怎样的错误呢，可以贴下吗

**Comment by JiongXing** [comment]
我新建工程，pod install 测试，没发现问题呢。你的工程是swift4不

**Comment by fuuqiu** [comment]
你好 我发现升级不到1.2.0版本 每次pod更新都是1.0.0 不知道如何解决

**Comment by JiongXing** [comment]
@fuuqiu 多个库？是指多个版本吗？`pod 'JXPhotoBrowser', '版本号'`
