### ISSUE TITLE
添加一个view视图 预览弹不出来

### ISSUE THREAD

**Issue by fuuqiu** [JiongXing/PhotoBrowser#64]
代码如下

` 
 let cellview =  MomentsTableViewCell()
        cellview.highQualityImageUrls = thumbnailImageSections
        cellview.thumbnailImageUrls = thumbnailImageSections
        cellview.overlayModels = overlayModelSections
        view.addSubview(cellview)
`

可以看到九张图,但是点击没有反应 不知道怎么修改

**Comment by JiongXing** [comment]
有没有完整点的代码让我看看，最好可以开个demo把问题复现下~

**Comment by fuuqiu** [comment]
我是直接new Cell 来使用,追加到当前的UIVIew 而不是填充到tableView  发现九宫图后面的cell高度只能覆盖第一排照片的顶部,点击第一排照片的顶部可以实现预览,我有手动去设置这个cell的高度 填充九宫格大小 然后就都能点击了 经过一番抽取 终于做出一个多图上传的界面了

**Comment by fuuqiu** [comment]
取消预览的时候 有提供回调函数么? 
取消预览时我看日志打印了:deinit:<JXPhotoBrowser.PhotoBrowser: 0x7fd8dc8b1e00>

**Comment by JiongXing** [comment]
嗯有的，`willDismiss`和`didDismiss`都有~

**Comment by JiongXing** [comment]
好的，能有帮助就好
