### ISSUE TITLE
func photoBrowser(_ photoBrowser: PhotoBrowser, localImageForIndex index: Int) -> UIImage?方法不执行

### ISSUE THREAD

**Issue by lynnx4869** [JiongXing/PhotoBrowser#65]
我用的swift4.1，库版本1.2.0，在项目中使用PhotoBrowser，想加载本地图片，但是debug的时候func photoBrowser(_ photoBrowser: PhotoBrowser, localImageForIndex index: Int) -> UIImage?没有执行。
请问我应该怎么展示本地图片？

**Comment by JiongXing** [comment]
您好，新版对本地图片的展示作了重构优化，现在可以这样：
```swift
PhotoBrowser.show(localImages: localImages, originPageIndex: index)
```

**Comment by JiongXing** [comment]
顺便想调查一下，原来的走代理方法，和新版本的传数组方法，更倾向于用哪种？

**Comment by JiongXing** [comment]
您好，我在1.3新版本支持了以前的方式。

**Comment by lynnx4869** [comment]
@JiongXing 我更喜欢代理方法

**Comment by lynnx4869** [comment]
@JiongXing 谢谢
