### ISSUE TITLE
第二次调用browser.show()黑屏

### ISSUE THREAD

**Issue by CoderHRXu** [JiongXing/PhotoBrowser#66]
只在在控制器中，配置好browser，点击按钮执行“browser.show()”，第一次能成功打开，消失之后，再点击按钮，黑屏。打开图层看到浏览器的图层是在控制器的后面。这是什么原因？
![image](https://user-images.githubusercontent.com/16515097/41109572-e4ca219a-6aa9-11e8-9c4d-5e6cc57f8b1c.png)

**Comment by JiongXing** [comment]
我看看

**Comment by JiongXing** [comment]
您好，那个demo可以发我看看么

**Comment by JiongXing** [comment]
图层在后面是没问题，我想找下黑屏原因

**Comment by CoderHRXu** [comment]
[BorwserDemo.zip](https://github.com/JiongXing/PhotoBrowser/files/2086925/BorwserDemo.zip)
两个按钮点击present，你对比一下

**Comment by JiongXing** [comment]
我看了Demo，建议在每次打开时去创建PhotoBrowser，消失时让它内存释放，而不要去强引用它。这样就好了

**Comment by CoderHRXu** [comment]
@JiongXing 1.我是这么想的，频繁创建和释放挺耗资源，所以想懒加载强引，需要用的时候弹出来，当然如果不强引用，这个问题能解决。 2.你对比一下我demo里面的两个按钮，同样都是present，你打开层级图对比一下，你会发现两个层级关系不一样，我不知道是什么原因；

**Comment by JiongXing** [comment]
好的，我看看怎么复用同一个PhotoBrowser
