### ISSUE TITLE
手势冲突有点问题

### ISSUE THREAD

**Issue by longios** [JiongXing/PhotoBrowser#7]
图片放大  scrollview的手势和 collectionView 的手势起冲突了

**Comment by JiongXing** [comment]
嗯，其中手势很多，也对此做了不少处理，你看到的是怎样的情况呢？

**Comment by longios** [comment]
恩，首先感谢楼主的回答。 就是图片放大之后的scrollview移制边缘的时候  继续右滑不能直接跳到下一张图片必须手放开在滑这里不知道用手势能否解决？  还有就是比如右滑过程中不想下一张了想左滑回去可能滑动速度比较快直接跳到上一张了

**Comment by JiongXing** [comment]
感谢提出，是有这两个问题，我想想看哈，好了再说~

**Comment by zhangyandong** [comment]
这个问题我试了苹果自己的照片应用也有只是没这么明显，另外个人比较倾向于用pageController

**Comment by JiongXing** [comment]
1. 图片放大之后的scrollview移制边缘的时候 继续右滑不能直接跳到下一张图片必须手放开在滑这里不知道用手势能否解决？ 
答：暂无优雅的解决办法。如果图片放大后，图片的右边缘未完全显示到屏幕上，这时从右往左滑动，事件的响应者是图片容器(ScrollView)，容器作出的响应是左移其内的图片，把未显示出来的图片部分显示出来。只要手指未松开，这个事件就未结束，事件响应者就无法切换到最外层的容器，而希望查看右侧的下一张图，只有最外层容器能做到。故在图片放大后，会需要额外多一次操作才能切换到下一张。
我还没找到有效的办法能省掉多出来的这一次操作。

**Comment by JiongXing** [comment]
1. 图片放大之后的scrollview移制边缘的时候 继续右滑不能直接跳到下一张图片必须手放开在滑这里不知道用手势能否解决？ 
答：暂无优雅的解决办法。如果图片放大后，图片的右边缘未完全显示到屏幕上，这时从右往左滑动，事件的响应者是图片容器(ScrollView)，容器作出的响应是左移其内的图片，把未显示出来的图片部分显示出来。只要手指未松开，这个事件就未结束，事件响应者就无法切换到最外层的容器，而希望查看右侧的下一张图，只有最外层容器能做到。故在图片放大后，会需要额外多一次操作才能切换到下一张。
我还没找到有效的办法能省掉多出来的这一次操作。

**Comment by JiongXing** [comment]
2.比如右滑过程中不想下一张了想左滑回去可能滑动速度比较快直接跳到上一张了。
答：这个问题我试过能解决，但同时却带来了其它的副作用，有点得不偿失。我看到苹果相册和微信的都有这个问题，只是易触发的程度不同。所以这个问题，我想暂时也不改它，其实从另一个角度看也许它不算问题，也有它合理的地方，就暂这样吧。感谢提出 ^^
