### ISSUE TITLE
下滑渐变缩放中，原点击view的图片为空白

### ISSUE THREAD

**Issue by deepindo** [JiongXing/PhotoBrowser#72]
当点击某个控件，放大显示图片浏览器后，再下滑渐变缩放中，原点击的控件显示的图片就为一片空白了，demo效果也是这样，还麻烦看看能不能更新一下。

![111](https://user-images.githubusercontent.com/18132241/41575214-93a1d678-73b4-11e8-8339-ebd1760309bd.png)

**Comment by JiongXing** [comment]
在scale转场模式下，可选择不隐藏关联缩略图。设置animationType = .scaleNoHiding即可。
