### ISSUE TITLE
关于横向布局的问题

### ISSUE THREAD

**Issue by weifans** [JiongXing/PhotoBrowser#75]
看了设计思路，非常棒的设计思路，优在细节！
不太理解为什么UICollectionView中嵌套UIScrollView？
UIScrollView就可以解决翻页，以及放大等问题，出于什么原因用了UICollectionView呢？

**Comment by JiongXing** [comment]
用UICollectionView是用它的复用cell能力呀

**Comment by weiFans** [comment]
我在尝试用此库浏览本地图片，有五千张图片，当我添加数据到500张左右时已经崩溃，我是取PHAsset全分辨率图像，也许是我使用方法不对...

我在尝试写一个类似的图片浏览库，思路是用UIScrollView作为浏览图主容器，始终维持三张图，当前显示页，以及左右隐藏页，所以几遍五千张，始终维持三张的内存。

本不想重复发明轮子，你的库很强大，但是封装的有点过度，我很认真的在看，还是整理不透，比如扩展视频浏览，支持播放，以及扩展照片编辑功能，需要对你的代码做大量的改动，决定基于你的重新一份。

**Comment by JiongXing** [comment]
几百张图以上的情况，我确实没关注。崩溃的原因你有没找到？我也试着找找看。然后上面提到的视频播放，我还有点计划，至于照片编辑功能，我想已经超出这个库的范围，应在另外的地方实现。若有需要提供帮助的地方，我尽量有时间就想想看。

**Comment by JiongXing** [comment]
新版已更新

**Comment by JiongXing** [comment]
您好，新版已完全重构，有空请更新到2.0看看~

**Comment by weifans** [comment]
好的，一定膜拜。
写了一个Android版的， Android有基础库支持，比swift简洁很多，需要可以看一下 [PhotoBrowse](https://github.com/weifans/PhotoBrowse)

**Comment by JiongXing** [comment]
不错，赞
