### ISSUE TITLE
PhotoBrowserCellPlugin 可否添加即将离开哪个 cell 的回调

### ISSUE THREAD

**Issue by hydyy** [JiongXing/PhotoBrowser#76]
插件的引入让这个组件更灵活，我遇到一些问题。

我在组件中做 video 的话，某些 cell 是需要的，某些是不需要的，要根据展示图片的类型做不一样的状态显示。
其次，在滑动离开 cell 之后，我需要对 cell 中的播放器进行停止操作。

所以，希望能增加进入，离开等状态，让开发可以更灵活

**Comment by hydyy** [comment]
额，还有 微信最新的展开收起动画已经改变了， 可否同步动画效果？ 感觉我要自己拉一份代码去改了。。。。

**Comment by JiongXing** [comment]
"做个 content，时间加在 content 上，然后把视图都加在 content 上，这样应该就没问题了"
这个可以再具体点讲讲吗

**Comment by JiongXing** [comment]
微信的动画变了吗？还没看到..

**Comment by hydyy** [comment]
是这样 现在plugin 视图加在 contentView 上，这样导致的问题是，在滑动事件时，你目前只处理到 imageview 我看效果猜测？ 

我的意思是做一个 customContent，所有的视图都去加在 customContent 上？这样一些手势事件都去针对 customContent 加。

微信在点击图片弹起之后，原视图目前是不做隐藏的，另外，在结束动画的处理上，如果是不一致的图片，会平滑很多，你看看？

我都有点不好意思了，有时间我就去写写给你提代码了，现在真的是一丢丢时间都没，项目太紧张了。

**Comment by hydyy** [comment]
![image](https://user-images.githubusercontent.com/1254987/42371823-24d7607c-8143-11e8-9b65-920cab611545.png)
![image](https://user-images.githubusercontent.com/1254987/42371831-2a92d7ee-8143-11e8-901a-e6ef56cd868a.png)

**Comment by JiongXing** [comment]
原始图不隐藏，可以设置 animationType = .scaleNoHiding。其它我也抽时间看看，也是忙哭

**Comment by hydyy** [comment]
嗯呐 我先 fork 一份自己改吧 哎 都是劳苦人民！

**Comment by hydyy** [comment]
我暂时做了 imageview 拖动的回调，去解决这个问题

**Comment by JiongXing** [comment]
你好，v1.4.0版本已更新：
- Cell 插件协议增加 CellWillDisplay 和 CellDidEndDisplaying 回调
- 图片下拉手势现在改为加在`cell.contentView`上
有空看看能不能解决你的问题 :)

**Comment by hydyy** [comment]
谢啦兄弟， 我尽快适配一下看看

**Comment by hydyy** [comment]
@JiongXing  是这样 我刚刚看了一下，只是把手势换到 contentView 上了，在拖动过程中，其实还是 imageView 在动，并不能解决我的问题，因为我的video 插件是加在 contentView 上的。

另外，微信在拖动过程中会隐藏 进度条等相关界面控件，所以可不可以再加一个 开始拖动，结束拖动的回调事件。

**Comment by hydyy** [comment]
刚刚试了一下 scrollToItem 这个方法，每次滑到第0张，加载新数据，index 是 newdatas.count ，但是结果不对，你可以试一下看看

**Comment by JiongXing** [comment]
我再完善一下，好了通知你

**Comment by hydyy** [comment]
谢兄弟

**Comment by JiongXing** [comment]
新版已完全重构，现在有了更好的扩展性，也可以任意继承cell，有空有兴趣可以看看~

**Comment by strangeliu** [comment]
新版本不支持原图隐藏了吗？

**Comment by JiongXing** [comment]
@strangeliu 新版本去掉了

**Comment by JiongXing** [comment]
3.0新版可同时支持多种Cell，若有需要，感兴趣可以看看
