### ISSUE TITLE
在显示状态下，更新 Data 后怎么处理界面

### ISSUE THREAD

**Issue by hydyy** [JiongXing/PhotoBrowser#78]
比如我显示的时候 datas 有10张，当滑动到第0张的时候，我要加载更多数据，插入到最前面，datas 里现在一共有20张 ，currentIndex 从0 变成了 10 这时候该怎么刷新整体？

**Comment by JiongXing** [comment]
试下这个，`PhotoBrowser`的实例方法
```swift
/// 重新加载数据源
open func reloadData()
```

**Comment by hydyy** [comment]
看到这个方法了，我检查到index==0去做刷新数据，数据插入到前面，这时候 index0 对应的其实是 newdatas.count 只刷新是没用的

**Comment by JiongXing** [comment]
你好，v.1.4.0版本增加`scrollToItem()`方法，可随时控制滑动到哪张图片 :)
