### ISSUE TITLE
有几个疑问

### ISSUE THREAD

**Issue by musicode** [JiongXing/PhotoBrowser#8]
我看了一下 readme，发现几个问题，望有空解惑。

1. 下方的 indicator，如果图片数组长度很大，是否没办法有效展示，我参考微信是没有这个组件的
2. 每张图片传入原图 url 和缩略图 url，那么展示时，我理解是先加载缩略图，然后再加载原图。这里存在一个问题，如果一张图片需要加载两次，这真的有必要么，除非缩略图已被缓存，在这个库中，是否已实现缓存？
3. 是否有“点击查看原图”，原图 url 肯定不能直接用于下载吧，如果那样做，一张大图可能好几 M 呢...
4. 左右滑动时图片的间隙，因为我不懂 ios，按我的理解，swiper 设计成每一页放一个组件（包含图片和下方的 indicator），每一页正好占满屏幕，这个间隙塞在哪呢？

**Comment by JiongXing** [comment]
1. 您说的下方indicator，应该是页码指示器？当图片数组长度很大时，只要不传pageControlDelegate给PhotoBrowser，指示器就不会出现。而还是需要页码指示的话，可以选用 3/75 这样的指示样式，都有实现。
2. 无论是缩略图或是原图，都有缓存的，第二次加载相同的url时，会直接使用缓存的图片。
3. 微信对同一张图片分成了3个级别，原图，大图，缩略图，在没进入浏览模式时显示缩略图，进入浏览模式后显示大图，点查看原图时再加载原图。我这里只作了2个级别，原图和缩略图，进入浏览模式加载完成后所看见的那张，就是原图了。
4. 这里设计成的一页，是超出了屏幕的，间隙在屏幕外。一页=显示的图片+右边间隙。这里为了处理间隙，确实花了不少功夫，也是难点所在。

其中第3点说到的“点击查看原图”，这个可以有哇。只是微信的话好像对图片大小有智能判断，有些图不大的话，是只对图片分2级，图很大就智能地分了3级。这点在客户端上可能做不到，需要服务端支持。而大多数App只分2级就已足够，它们更愿意进入浏览即看见原图。
看看需求强烈的话，我加上。再次感谢提示 ^ ^

**Comment by musicode** [comment]
那么是否可以改造下数据格式，如果三种图片都传了 size，你就可以明确知道是否需要显示“点击查看原图”，如果不传 size，就跟现在一样呗

**Comment by musicode** [comment]
对于 4，按你的说法应该是

```
前一页图片（屏幕外） + 间隙（屏幕外） + 当前页图片 + 间隙（屏幕外）+ 后一页图片（屏幕外）
```

不论左右滑动，都能先看到间隙。

这里我有个疑问，以前一页为例，在不可见的情况下，前一页图片左侧是否还需要间隙？

如果不需要，那么前一页在不可见时，是否要把图片缩小一些，以容纳间隙，即：

```
屏幕宽度 = 缩小的图片宽度 + 间隙宽度
```

当滑到前一页时，以动画的形式，放大图片，缩小间隙？

是这样么？

**Comment by JiongXing** [comment]
1.“点击查看原图”这个功能我会做的，有空弄下。
2.不需要把图片缩小啊。图片和间隙，它们是并列关系，都是由外面的容器管理的，我这里做的操作只负责调整容器的展示区域...

**Comment by musicode** [comment]
按你的说法，我理解 ios 里面的 swiper 就是一个横向的很长的一个视图，自己处理手势滑动是么，这样的话，难度就转移给滑动逻辑了

**Comment by JiongXing** [comment]
它表现出来的样子的确是像一个横向很长的视图，实际上并不会，容器会做视图的复用，于内存中的只有两三页，不断复用。如何复用，这个问题由iOS的UICollectionView做了，我直接拿来用。

**Comment by musicode** [comment]
UICollectionView 就是当前页 + 前后页 呗，滑动的时候回收再利用已创建的，这个属于底层技术问题。

现在不管有没有这个优化策略，即使两三页，滑动到下一页这种需求，实现方式是通过手势滑动的距离来判断是否到了下一页么？

但这样说不通啊，如果 UICollectionView 按页来缓存，它怎么知道多宽是一页呢，我理解它的逻辑应该是这样的吧：

```
page + page + page + page
```

一屏为一页，UICollectionView 不管每页的内容。

如果是这样，手势滑动翻页应该由 UICollectionView 接管才对，你咋能拦截这种行为呢

**Comment by JiongXing** [comment]
噢，UICollectionView是不知道一页的多宽的，你说的"手势滑动翻页应该由 UICollectionView 接管才对，你咋能拦截这种行为呢"，这行为确实是我做的。
UICollectionView作为一个容器，它允许自定义其内的元素如何布局，这时需要提供一个布局类给容器。
这个类在本项目中是`PhotoBrowserLayout`，它是一个流式布局，其内有一个核心方法，用于控制在滑动停下来时，应把内容视图调整到什么位置。这个方法是

    /// 调整scroll停下来的位置
    override public func targetContentOffset(forProposedContentOffset proposedContentOffset: CGPoint, withScrollingVelocity velocity: CGPoint) -> CGPoint {
        // 页码
        var page = round(proposedContentOffset.x / pageWidth)
        // 处理轻微滑动
        if velocity.x > 0.2 {
            page += 1
        } else if velocity.x < -0.2 {
            page -= 1
        }
        // 一次滑动不允许超过一页
        if page > lastPage + 1 {
            page = lastPage + 1
        } else if page < lastPage - 1 {
            page = lastPage - 1
        }
        if page > maxPage {
            page = maxPage
        } else if page < minPage {
            page = minPage
        }
        lastPage = page
        return CGPoint(x: page * pageWidth, y: 0)
    }

**Comment by musicode** [comment]
多谢，大概知道了~

**Comment by JiongXing** [comment]
增加查看原图功能，支持3种清晰度图片

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/27822313-d10242c8-60d7-11e7-935a-41666a0f7775.png)

刚试下了 master 的 demo，没有什么操作按钮啊（查看原图）

另外页码指示器，一会是在上面的 (current/total) 格式，一会是底部的 点点点 格式，没发现有啥规律。。。

**Comment by JiongXing** [comment]
1.Demo的代码没有给原图url，所以也就没有显示查看原图按钮~~
2.Demo的代码让页码指示器随机出现在上方或下方，每次打开都是随机..

**Comment by musicode** [comment]
当显示一页图片时，你会判断这张图是否已加载过么？比如如果之前点击过查看原图，下次再看到这张图，是否直接显示缓存里的原图？

**Comment by musicode** [comment]
数字型 和 点点型 的页面，可以配置么，比如总页数 < 10时，显示点点，>= 10 显示数字？

**Comment by musicode** [comment]
还有个疑问，一般图片列表是调起 photo browser 的入口，图片列表里的图片都是小图，比如 50 x 50，点击这种小图调起 photo browser，这时你默认会加载最高清的图片，如果从没加载过，你会先加载这个 50 x 50 么，我看微信的效果是 小图+loading 同时显示，加载成功则换成和屏幕等宽的缩略图，点击原图才是最高清的。

这里存在一个问题，就是图片列表属于业务代码，而 photo browser 属于库，如果库不知道业务代码缓存图片的策略，调起库时，首先加载那张小图（50x50）是否很傻逼，因为显示这个小图只是为了过渡一下，立刻就切成缩略图了把

**Comment by JiongXing** [comment]
1.数字型 和 点点型 的页面，可以配置么，比如总页数 < 10时，显示点点，>= 10 显示数字？

**Comment by JiongXing** [comment]
1.数字型 和 点点型 的页面，可以配置么，比如总页数 < 10时，显示点点，>= 10 显示数字？
可以的，自己判断总页数，然后根据判断结果决定配置哪种样式
2.如果从没加载过的图片，会先显示50x50的，同时显示loading并下载高清图，在高清图下载完成后把50x50替换成高清图，此时如果还有配置原图url，则会显示查看原图按钮，点击查看原图就会下载原图，原图下载完成后替换高清图
3.框架有自己的一套缓存，如果业务代码也实现了自己的缓存，框架是不会读取业务代码的图片缓存的
