### ISSUE TITLE
ImageView 设置为 AnimatedImageView 类时候 播放不了 GIF 

### ISSUE THREAD

**Issue by williamxiewz** [JiongXing/PhotoBrowser#80]
ImageView 设置为 AnimatedImageView 类时候 播放不了 GIF

**Comment by JiongXing** [comment]
Kingfisher的问题 - -|。有时间你先试试自己做个PhotoLoader，自己加载图片。我迟些时候再验证你的问题

**Comment by JiongXing** [comment]
使用UIImageView就可以正常播放了。你说的AnimatedImageView不太清楚具体是怎样实现的，可以改为系统的UIImageView试试不？
