### ISSUE TITLE
覆盖了很多层浏览图层，导致状态栏看不见 但是 又不影响界面的操作

### ISSUE THREAD

**Issue by codeAndylau** [JiongXing/PhotoBrowser#81]
我使用的是类方法展示的浏览图层 PhotoBrowser.show(delegate: self, originPageIndex: indexPath.item) 。最后的结果就是状态栏看不见了 ，之后推出app才能再次进来就正常了。

**Comment by JiongXing** [comment]
进入PhotoBrowser后是故意遮挡状态栏的，退出PhotoBrowser就会还原的。你遇到的问题可以再具体描述吗，或者有没有Demo能重现

**Comment by codeAndylau** [comment]
没有demo呢 项目太大了 没法上传，这个问题也不是毕现的，我现在遇到的问题就是  点击要展示的图片打开图片浏览器的时候浏览器是打开了 但是感觉这个图片浏览器就像透明的一样，能全不看见下面的视图，但是图片浏览器又会把状态栏给隐藏 ，而且在点击操作的时候 图片浏览器不会消失了。会呈现很多层图片浏览器，导致只有推出app了 才能在使用，我不知道这样描述准不准确 0.0

**Comment by JiongXing** [comment]
我再细查一下

**Comment by codeAndylau** [comment]
我现在 发现一个规律  调试的手机是6s。反正就是隔了一天在打开app 第一次会出现这种情况 然后推出app 在重新打开就好了

**Comment by acenqiu** [comment]
如果做识别图片二维码的功能，需要 present 一个 SafariViewController，这个时候会导致状态栏不可见。

**Comment by codeAndylau** [comment]
大神。其实 我没有做识别功能。但是像你说这个这个该怎么来实现呢

**Comment by JiongXing** [comment]
状态栏是否需要覆盖，我还是提供接口出来让你们控制吧

**Comment by codeAndylau** [comment]
0.0

**Comment by JiongXing** [comment]
抱歉拖更了。这周末我抽时间写

**Comment by JiongXing** [comment]
新版已更新
