### ISSUE TITLE
默认的插件在X下显示位置重叠了

### ISSUE THREAD

**Issue by fanglinwei** [JiongXing/PhotoBrowser#82]
默认的control空间和查看原图插件在iPhoneX下显示重叠在一起了

<img width="375" alt="aa531d1a-da8f-44c4-9bc3-dc834461cef0" src="https://user-images.githubusercontent.com/16839723/42990133-67eb417a-8c34-11e8-8e4d-7241567c3241.png">

**Comment by JiongXing** [comment]
感谢反馈

**Comment by JiongXing** [comment]
新版已更新
