### ISSUE TITLE
是否未完成

### ISSUE THREAD

**Issue by zzz1029335886** [JiongXing/PhotoBrowser#84]
查看原图组件，按钮没有显示，是否还未完成

**Comment by JiongXing** [comment]
delegate实现这个方法并返回url：
```swift
func photoBrowser(_ photoBrowser: PhotoBrowser, rawUrlForIndex index: Int) -> URL?
```
就会显示了

**Comment by zzz1029335886** [comment]
没有啊，刚clone的

**Comment by zzz1029335886** [comment]
不行，我看了那个查看原图的组件，但是没看到按钮什么时候加上去的。ps，自定义很不错，可以下面的这个样式吗
![image](https://user-images.githubusercontent.com/16664476/43566348-b0916766-9660-11e8-8bc2-b5c908b69668.png)

**Comment by zzz1029335886** [comment]
不好意思，看到在哪加了

**Comment by JiongXing** [comment]
嗯，上面效果图是可以支持的，你再看看，实在不会的话我尽量提供帮助
