### ISSUE TITLE
最新版本，打开怎么黑屏呢

### ISSUE THREAD

**Issue by yanrongxiang** [JiongXing/PhotoBrowser#85]

**Comment by JiongXing** [comment]
有Demo发我不，我帮你改下

**Comment by yanrongxiang** [comment]
请问这有什么问题吗

![default](https://user-images.githubusercontent.com/3411744/43935034-a54c8d16-9c84-11e8-9da4-77402e9a0946.png)


![default](https://user-images.githubusercontent.com/3411744/43935019-91b87ff8-9c84-11e8-9a4b-71701ed09f38.png)

**Comment by yanrongxiang** [comment]
协议方法都执行了，出来就是黑屏

**Comment by JiongXing** [comment]
在这里返回你的bannerView看看
```
func photoBrowser(_ photoBrowser: PhotoBrowser, thumbnailViewForIndex index: Int) -> UIView?
```

**Comment by yanrongxiang** [comment]
一定要实现这个协议吗，不好意思才发现用的是scale动画，谢谢，现在正常了，建议如果使用scale并且没有实现photoBrowser(_ photoBrowser: PhotoBrowser, thumbnailViewForIndex index: Int) -> UIView?协议可以给个提示^_^
