### ISSUE TITLE
GIF图片怎么不动？

### ISSUE THREAD

**Issue by powerDJL** [JiongXing/PhotoBrowser#86]
看到项目已经支持gif了，但是打开一个gif图地址，只有静态图片，没有动态播放。

**Comment by JiongXing** [comment]
不能够吧...

**Comment by powerDJL** [comment]
gif需要什么特殊的设置吗？

另外，我按照你的说明里的方式 支持webp格式的图片。
 pod 'JXPhotoBrowser/KingfisherWebP'
当打开一个图片时，会进入这个断言。(使用 pod 'JXPhotoBrowser‘ 时不会出问题。)
`let cls = NSClassFromString("KingfisherPhotoLoader")
          assert(cls != nil, "请传入你实现的 photoLoader 或在 Podfile 选用 Kingfisher subspec!")`

**Comment by JiongXing** [comment]
webp这里有个小bug。昨晚修复了，还没发到cocoapods更新

**Comment by JiongXing** [comment]
gif不需要设置的啊

**Comment by powerDJL** [comment]
demo 是可以播的，我再找找自己的问题吧。

**Comment by JiongXing** [comment]
新版已更新
