### ISSUE TITLE
Gif 从缓存中读取后,无法播放

### ISSUE THREAD

**Issue by yolande520** [JiongXing/PhotoBrowser#9]
/// 取已有图像，若有高清图，只返回高清图，否则返回缩略图和url
    private func imageFor(index: Int) -> (UIImage?, URL?) {
        if let highQualityImage = photoBrowserDelegate.photoBrowser(self, highQualityImageForIndex: index) {
            return (highQualityImage, nil)
        }
        var highQualityUrl: URL?
        if let url = photoBrowserDelegate.photoBrowser(self, highQualityUrlStringForIndex: index) {
            var cacheImage: UIImage?
            let result = KingfisherManager.shared.cache.isImageCached(forKey: url.cacheKey)
            if result.cached, let cacheType = result.cacheType {
                switch cacheType {
                case .memory:
                    cacheImage = KingfisherManager.shared.cache.retrieveImageInMemoryCache(forKey: url.cacheKey)
                case .disk:
                    cacheImage = KingfisherManager.shared.cache.retrieveImageInDiskCache(forKey: url.cacheKey)
                default:
                    cacheImage = nil
                }
            }
            if cacheImage != nil {
                return (cacheImage!, nil)
            }
            highQualityUrl = url
        }
        let thumbnailImage = photoBrowserDelegate.photoBrowser(self, thumbnailImageForIndex: index)
        return (thumbnailImage, highQualityUrl)
    }

**Comment by JiongXing** [comment]
感谢提出，已修复
