### ISSUE TITLE
WkWebView上实现预览功能，又想要动画效果

### ISSUE THREAD

**Issue by speeddream** [JiongXing/PhotoBrowser#90]
在WkWebView上是获取不到这个imageview， 但是可以获取到image这个元素的rect（getBoundingClientRect）。PhotoBrowserDelegate可否增加方法，依据image动画前后的rect做动画效果。

**Comment by JiongXing** [comment]
可以支持，我想下

**Comment by JiongXing** [comment]
您好，新版本已支持传入rect，有空请更新到2.0看看~

**Comment by speeddream** [comment]
好的，非常感谢作者，给力😀
