### ISSUE TITLE
关于Swift4.2的支持

### ISSUE THREAD

**Issue by lynnx4869** [JiongXing/PhotoBrowser#91]
我用cocoapods安装最新的库，默认对swift4.2增加了支持，但是编译结果并没有对swift4.2支持，是否是.podspec文件中没有增加swift版本描述？s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4.0' }

![image](https://user-images.githubusercontent.com/11997318/45668467-6a001180-bb4f-11e8-88d8-5245d1af23f0.png)

**Comment by lynnx4869** [comment]
@JiongXing 我现在已经改了target的swift支持了，项目.podspec文件默认swift版本会自动设置的吧，希望可以加上

**Comment by JiongXing** [comment]
好的，感谢反馈

**Comment by chaoshenglu** [comment]
有临时解决方案吗？

**Comment by JiongXing** [comment]
有，今天更新

**Comment by JiongXing** [comment]
已更新到4.2，看看

**Comment by JiongXing** [comment]
已解决.
