### ISSUE TITLE
进度条加载图片回调，没有清空进度掉

### ISSUE THREAD

**Issue by shen0607** [JiongXing/PhotoBrowser#93]
/// 加载图片完成
    public func photoBrowserCellDidLoadImage(_ cell: PhotoBrowserCell, placeholder: UIImage?, url: URL?) {
        progressView(for: cell)?.isHidden = true
    }
进度条加载高清图片完成后，没有清空进度掉，导致查看原图的时候，进度条先填满，然后又清空。

**Comment by JiongXing** [comment]
可以有代码给我，或录屏演示吗？

**Comment by shen0607** [comment]
这个是测试的 
![image](https://user-images.githubusercontent.com/26315997/46844505-fb3e6d00-ce09-11e8-9ffb-858749306682.png)

**Comment by JiongXing** [comment]
您好，新版已完成，有空请更新到2.0版本再看看

**Comment by shen0607** [comment]
好的，我试试看

**Comment by shen0607** [comment]
这个  问题 还是没解决，有高清图和 原图的时候，点击原图的时候，加载的圆圈显是填满的状态，然后再为空，再重新加载。

**Comment by JiongXing** [comment]
稍等，再发个版解决

**Comment by JiongXing** [comment]
大兄弟，更新到2.0.3应该好了

**Comment by shen0607** [comment]
这个问题还是存在，最新的2.0.4

**Comment by JiongXing** [comment]
更新到2.0.5看看，应该可以了

**Comment by shen0607** [comment]
更新了，还是一样的问题哦

**Comment by JiongXing** [comment]
有空在我的示例工程里面重现出来不？上传代码给我，我查下

**Comment by JiongXing** [comment]
我根据猜测尝试在2.0.6修复，看看有没效果

**Comment by JiongXing** [comment]
这里有验证没？

**Comment by JiongXing** [comment]
先关闭这个issue，如果还有问题，可重新打开
