### ISSUE TITLE
你好我下了更新了最新的不能使用6个错误

### ISSUE THREAD

**Issue by kmheike** [JiongXing/PhotoBrowser#94]
我是 XCODE9.3 下了你 demo 也是无法使用方便加个 QQ 我截图给你看吗

**Comment by JiongXing** [comment]
要求xcode10，需要swift 4.2呢

**Comment by kmheike** [comment]
麻烦了

**Comment by kmheike** [comment]
为什么不支持9.3呢我硬盘不够升级了

**Comment by kmheike** [comment]
请问下我现在的项目是在9.3上写的，我升级到10会不会打不开了报错什么的

**Comment by JiongXing** [comment]
升到10，你要修改为swift4.2的语法，还是很好改的

**Comment by JiongXing** [comment]
已在README补充说明：
Archive 打包错误
如果出现：

While deserializing SIL vtable for ...
abort trap 6
请升级你的工程到Swift4.2，即可解决。
