### ISSUE TITLE
是不是必须 要 xcdoe10

### ISSUE THREAD

**Issue by kmheike** [JiongXing/PhotoBrowser#95]
是不是必须 要 xcdoe10我是9.3一直报错

**Comment by JiongXing** [comment]
是的啊。主要是要swift4.2编译器

**Comment by JiongXing** [comment]
已在README补充说明：
Archive 打包错误
如果出现：

While deserializing SIL vtable for ...
abort trap 6
请升级你的工程到Swift4.2，即可解决。
