### ISSUE TITLE
pod下来无法使用

### ISSUE THREAD

**Issue by dqthrow** [JiongXing/PhotoBrowser#96]
你好,我pod 下来无法使用 xcode10 Module 'JXPhotoBrowser' has no member named 'BaseDelegate'
请问是什么原因呢

**Comment by dqthrow** [comment]
pod 只有指定版本才能使用 pod 'JXPhotoBrowser' , '2.0.0'
下面这句代码 在xcode10上 pod 'JXPhotoBrowser' , '2.0.0' 会出现报错
报错类容: Type of expression is ambiguous without more context

let trans = JXPhotoBrowser.ZoomTransitioning { (browser, index, view) -> UIView? in
    let indexPath = IndexPath(item: index, section: 0)
    return collectionView.cellForItem(at: indexPath)
}
楼主麻烦看下呢 这个报错需要怎么解决才入坑swift 求解决~~

**Comment by JiongXing** [comment]
可以开个工程重现你的问题，打包上传给我吗？我查下

**Comment by JiongXing** [comment]
@dqthrow 2.0.7对类重命名了，你稍微修改一下，主要就是把JXPhotoBrowser.Xxx的点号去掉

**Comment by dqthrow** [comment]
> 可以开个工程重现你的问题，打包上传给我吗？我查下

[SwiftText.zip](https://github.com/JiongXing/PhotoBrowser/files/2500056/SwiftText.zip)
打包上传了几次, 没找到自己回复的问题... 请问是什么原因导致无法找到库的类呢.

**Comment by dqthrow** [comment]
非常感谢,最新的版本之前的demo不一样了 我没注意 三克油 已经正常使用了!
