### ISSUE TITLE
集成SDK 打包问题

### ISSUE THREAD

**Issue by shen0607** [JiongXing/PhotoBrowser#97]
你好，集成了 你的SDK，打包的时候报这个错误：
2.	While running pass #1 SILModuleTransform "PerformanceSILLinker".

3.	While deserializing SIL vtable for 'NumberPageControlDelegate' in module 'JXPhotoBrowser'

error: Abort trap: 6

![image](https://user-images.githubusercontent.com/26315997/47250092-bdb39280-d44e-11e8-814c-e379cb977cb8.png)

**Comment by Tank** [comment]
我也遇到同样的问题，把Core/JXPhotoBrowser.swift中的deinit去掉就可以打包了，能否修复一下？
![image](https://user-images.githubusercontent.com/63062/47250143-58ac6c80-d44f-11e8-87f7-24bf978b8e68.png)

**Comment by JiongXing** [comment]
@Tank 我先去掉deinit发下小版，你们看看

**Comment by JiongXing** [comment]
2.0.6已发布，试试

**Comment by shen0607** [comment]
换了 2.0.6，还是无法打包 ，一样的问题。

**Comment by shen0607** [comment]
![image](https://user-images.githubusercontent.com/26315997/47252289-dfc00b80-d474-11e8-8e35-5527c3e63c04.png)

**Comment by JiongXing** [comment]
那上面的兄弟说的删掉deinit，还是没作用。
这个问题我估计是因为因为类声明在了extension里导致的，可能要把它们都挪出来成为一级类才行。
本来是参考swift4.2的风格写的，没想到xcode有这坑。。。

**Comment by shen0607** [comment]
大佬，这个问题你什么会更新？

**Comment by JiongXing** [comment]
现在整

**Comment by Tank** [comment]
@JiongXing 感谢支持，刚有事没及时回复，更新了后可以打包了。@shen0607 我是直接用JXPhotoBrowser(dataSource: dataSource).show(pageIndex: indexPath.item)，没有用自定义代理

**Comment by shen0607** [comment]
有最新demo么，改版了 有些API不能用了（比如查看原图的那个）

**Comment by JiongXing** [comment]
@shen0607 所有API都能用的啊，只是重命名了类，demo都同步更新了，下载master就行

**Comment by shen0607** [comment]
@JiongXing 下载demo可以了，代码也改过来了，只是 打包还是这个问题。
![image](https://user-images.githubusercontent.com/26315997/47254376-3557e080-d494-11e8-8a04-30ae7f74191d.png)
之前1.6的是没有这个问题。

**Comment by JiongXing** [comment]
醉了，换个电脑打包试试

**Comment by meiziteacher** [comment]
<img width="662" alt="screen shot 2018-10-20 at 18 42 53" src="https://user-images.githubusercontent.com/36841371/47254671-0fccd600-d498-11e8-8095-b64438d40cb5.png">
还是archive 打包时错误

**Comment by JiongXing** [comment]
哪位帮查到原因，请告之~

**Comment by shen0607** [comment]
是不是Swift的版本要求？我是4.0的

**Comment by JiongXing** [comment]
是4.2语法

**Comment by shen0607** [comment]
大佬，可以支持4.0的语法么？目前就是这几个JXPhotoBrowserBaseDelegate、JXDefaultPageControlDelegate、JXNumberPageControlDelegate不行，我项目如果更新到4.2语法，有上千个修改。

**Comment by shen0607** [comment]
下载到本地可以了，要修改两个地方：
![image](https://user-images.githubusercontent.com/26315997/47276614-fd16e600-d5ea-11e8-94da-106fe915c2ab.png)
![image](https://user-images.githubusercontent.com/26315997/47276626-10c24c80-d5eb-11e8-8753-74b9afe6ea0d.png)

**Comment by JiongXing** [comment]
先关闭这个issue，如果有人遇到这个问题，可以这样做：
如果使用pod，则把你的工程升到Swift4.2；
或者手动导入本库代码，修改为你工程Swift版本的语法。
